name: 'Publish Docker Image'
description: 'Build and publish Docker image to GitHub Container Registry.'
inputs:
  TOKEN:
    description: 'github token'
    required: true
  GITHUB_ACTOR:
    description: 'github_actor'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 10

    - name: Login to Github
      uses: docker/login-action@v3.4.0
      with:
        registry: ghcr.io
        username: ${{ inputs.GITHUB_ACTOR }}
        password: ${{ inputs.TOKEN }}

    - name: Build and Publish Docker Images
      id: docker-publish
      shell: bash
      run: |
        sleep 90   # give npmjs registry enough time to be ready with the newly published packages (check if this delay is still needed)

        # set the branch name before checking out tag
        BRANCH=$(git rev-parse --abbrev-ref HEAD)
        echo "::set-output name=branch::$BRANCH"

        git pull origin $BRANCH # in case this action is not able to access a pushed tagged commit/branch tip from a previous step within the CI environment
        
        # should detect and pull latest tag in branch and build from it,
        # and avoid building from branch HEAD/tip that may have already moved
        TAG="v$(node -p "require('./package.json').version")"
        git fetch --tags --quiet origin $TAG # always use tagged commit for build 
        git checkout $TAG

        cd container;
        ./build2.sh -r "ghcr.io/stjude/" server;
        TAG="$(node -p "require('./server/package.json').version")";
        HASH="$(git rev-parse --short HEAD)";
        docker push "ghcr.io/stjude/ppserver:$TAG-$HASH";
        docker push "ghcr.io/stjude/ppserver:latest";
        
        ./build2.sh -r "ghcr.io/stjude/" full;
        TAG="$(node -p "require('./full/package.json').version")";
        docker push "ghcr.io/stjude/ppfull:$TAG-$HASH";
        docker push "ghcr.io/stjude/ppfull:latest";
        
        echo "::set-output name=docker_version::$TAG-$HASH";

    - name: get pp version
      id: pp-version
      uses: martinbeentjes/npm-get-version-action@main

    - name: get front version
      id: front-version
      uses: martinbeentjes/npm-get-version-action@main
      with:
        path: front

    - name: get server version
      id: server-version
      uses: martinbeentjes/npm-get-version-action@main
      with:
        path: server

    - name: Run deploy action
      uses: peter-evans/repository-dispatch@v2
      if: ${{ !startsWith(github.ref_name, 'release') && !startsWith(github.ref_name, 'prerelease') }}
      with:
        token: ${{ inputs.TOKEN }}
        repository: stjude/sj-pp
        event-type: version-update
        client-payload: '{"pp_version": "${{ steps.pp-version.outputs.current-version }}", "front_version": "${{ steps.front-version.outputs.current-version }}", "server_version": "${{ steps.server-version.outputs.current-version}}", "docker_version": "${{ steps.docker-publish.outputs.docker_version}}", "branch": "${{ steps.docker-publish.outputs.branch }}"}'
