#!/bin/bash

STAGEDFILES="$(git diff --name-only --cached)"
if [[ "$STAGEDFILES" == *"release.txt"* ]]; then
  echo "skipped release note detection since release.txt is already staged"
  exit 0
fi

MSG="$(cat $1)"
NOTES="$(cat release.txt)"

if [[ "$MSG" == *"fix: "* || "$MSG" == *"feat: "* ]]; then
  echo "adding release notes ..."  
  NOTES=$(node ./build/setReleaseText.js release.txt "$1")
  echo -e "$NOTES" > release.txt
  if [[ "$(git diff --name-only release.txt)" == 'release.txt' ]]; then
    git add release.txt
  fi
fi

exit 0
