#!/bin/sh

set -e

FILES=$(git diff-tree --no-commit-id --name-only --diff-filter=ACM -r origin/master..HEAD)
echo "number of files to be checked=$(echo "$FILES" | wc -w)"
# doing this per GDC requirements
pre-commit run --files $FILES
# run linter on ts files
echo "linting ..."
# echo "$FILES" | grep "\.ts" | xargs npx eslint
echo "$FILES" | grep "shared\/" | grep "\.ts" | xargs npx eslint # eslint.config.js defaults to shared-node-browser
echo "$FILES" | grep "client\/" | grep "\.ts" | JSENV=browser xargs npx eslint
echo "$FILES" | grep "front\/" | grep "\.ts" | JSENV=browser xargs npx eslint
echo "$FILES" | grep "python\/" | grep "\.ts" | JSENV=node npx eslint
echo "$FILES" | grep "rust\/" | grep "\.ts" | JSENV=node xargs npx eslint
echo "$FILES" | grep "server\/" | grep "\.ts" | JSENV=node npx eslint
exit 0
