#!/bin/sh

set -e

FILES=$(git diff --cached --name-only --diff-filter=ACM "*.js" "*.ts" "*.mjs" "*.cjs" | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

echo "Prettifying $FILES ..."

# Prettify all selected files
# configuration are under the `"prettier": {}` object in package.json
echo "$FILES" | xargs npx prettier --no-semi --use-tabs --write

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

# doing per GDC requirements
pre-commit run --files "$FILES"

# lint against team preferences
echo "Linting ..."
echo "$FILES" | grep "\.ts" | xargs npx eslint

# check for invalid use of .Inner reference
PRODINNER=$(echo "$FILES" | xargs grep -lr --exclude=\*.spec\* --exclude=\*dist/\* --exclude=\*test/\* --exclude=\*.md "\.Inner\.")
if [[ "$PRODINNER" != "" ]]; then
	echo "\n--- !!! invalid use of .Inner found in: !!! ---"
	echo "$PRODINNER\n"
	exit 1
fi 

exit 0
