import type { LlmConfig, DbRows, GeneDataTypeResult, term } from '#types'
import { FILTER_TERM_DEFINITIONS, validate_filter } from './filter.ts'
import { formatTrainingExamples, extractGenesetsFromPrompt, buildCommonPrompt, readJSONFile } from './utils.ts'
import { route_to_appropriate_llm_provider } from './routeAPIcall.ts'
import path from 'path'
import fs from 'fs'

type TermCategory = 'categorical' | 'float' | 'integer' | undefined

// Default chart type for each (normalized cat1, normalized cat2) combination
const CHILD_TYPE_DEFAULTS: Record<string, string> = {
	'categorical:undefined': 'barchart',
	'numeric:undefined': 'violin',
	'categorical:categorical': 'barchart',
	'numeric:categorical': 'violin',
	'categorical:numeric': 'violin',
	'numeric:numeric': 'sampleScatter'
}

// Overrides that are invalid (produce an error) for a given combination
const CHILD_TYPE_INVALID: Record<string, Set<string>> = {
	'categorical:undefined': new Set(['violin', 'boxplot', 'sampleScatter']),
	'categorical:categorical': new Set(['violin', 'boxplot', 'sampleScatter'])
}

export async function extract_summary_terms(
	prompt: string,
	llm: LlmConfig,
	dataset_db_output: { db_rows: DbRows[]; rag_docs: string[] },
	dataset_json: any,
	ds: any,
	testing: boolean,
	genesetNames: string[] = [],
	geneFeatures: GeneDataTypeResult[],
	aiFilesDir: string
) {
	const common_genes = geneFeatures.map(g => g.gene)
	const Schema = {
		$schema: 'http://json-schema.org/draft-07/schema#',
		$ref: '#/definitions/SummaryType',
		definitions: {
			SummaryType: {
				type: 'object',
				properties: {
					term: { $ref: '#/definitions/termwrapper', description: 'Name of 1st term' },
					term2: { $ref: '#/definitions/termwrapper', description: 'Name of 2nd term' },
					term0: { $ref: '#/definitions/termwrapper', description: 'Name of 3rd term' },
					simpleFilter: {
						type: 'array',
						items: { $ref: '#/definitions/FilterTerm' },
						description: 'Optional simple filter terms'
					},
					childType: {
						type: 'string',
						enum: ['violin', 'boxplot', 'sampleScatter', 'barchart'],
						description:
							'Optional explicit child type requested by the user. If omitted, the logic of the data types picks the child type.'
					}
				},
				required: ['term', 'simpleFilter'],
				additionalProperties: false
			},
			termwrapper: {
				type: 'object',
				properties: {
					term: {
						$ref: '#/definitions/term',
						description:
							'Name of term which can be either a dictionary term or a gene term or a coordinate term or a metabolite term'
					},
					q: {
						$ref: '#/definitions/q',
						description:
							'Optional query parameters to further specify the term, such as the mode and type of binning for a term'
					}
				},
				required: ['term'],
				additionalProperties: false
			},
			term: {
				oneOf: [
					{ $ref: '#/definitions/DictionaryTerm' },
					{ $ref: '#/definitions/GeneTerm' },
					{ $ref: '#/definitions/CoordinateTerm' },
					{ $ref: '#/definitions/MetaboliteTerm' }
				]
			},
			DictionaryTerm: {
				type: 'object',
				properties: {
					dictionaryTerm: { type: 'string', description: 'Term that corresponds to dictionary terms in the dataset db' }
				},
				required: ['dictionaryTerm'],
				additionalProperties: false
			},
			GeneTerm: {
				type: 'object',
				properties: {
					gene: { type: 'string', description: 'Name of the gene' },
					dataType: {
						type: 'string',
						enum: ['geneExp', 'proteome', 'variant', 'methylation'],
						description: 'Data type of the gene term'
					}
				},
				required: ['gene', 'dataType'],
				additionalProperties: false
			},
			CoordinateTerm: {
				type: 'object',
				properties: {
					chr: { type: 'string', description: 'Chromosome' },
					start: { type: 'number', description: 'Start site' },
					stop: { type: 'number', description: 'Stop site' },
					dataType: {
						type: 'string',
						enum: ['meth', 'geneExp'],
						description: 'Data type of the genomic coordinates'
					}
				},
				required: ['chr', 'start', 'stop', 'dataType'],
				additionalProperties: false
			},
			MetaboliteTerm: {
				type: 'object',
				properties: {
					metabolite: { type: 'string', description: 'Name of the metabolite' },
					dataType: {
						type: 'string',
						enum: ['metIntensity'],
						description: 'Data type of the metabolite term'
					}
				},
				required: ['metabolite', 'dataType'],
				additionalProperties: false
			},
			q: {
				type: 'object',
				properties: {
					mode: {
						type: 'string',
						enum: ['binary', 'discrete', 'continuous'],
						description: 'Mode of the term'
					},
					type: {
						type: 'string',
						enum: ['custom-bin', 'regular-bin'],
						description: 'Type of binning'
					},
					bins: { type: 'number', description: 'Number of bins' }
				},
				required: ['mode', 'type'],
				additionalProperties: false
			},
			...FILTER_TERM_DEFINITIONS
		}
	} // This JSON schema is generated by ts-json-schema-generator. When SummaryType is updated, please update this schema by uncommenting the above code and running it locally
	console.log('Extracted JSON schema for SummaryType:', JSON.stringify(Schema))
	const matchedGenesets = extractGenesetsFromPrompt(prompt, genesetNames)

	// Read Summary agent-specific JSON file
	if (!fs.existsSync(path.join(aiFilesDir, 'summary.json')))
		throw 'Summary agent file is not specified for dataset:' + ds.label
	const summary_ds = await readJSONFile(path.join(aiFilesDir, 'summary.json'))
	if (!summary_ds) throw 'Summary information is not present in the dataset file.'
	if (summary_ds.TrainingData.length == 0) throw 'No training data is provided for the summary agent.'

	const training_data = formatTrainingExamples(summary_ds.TrainingData)

	const system_prompt =
		'I am an assistant that extracts the summary terms from user query. The final output must be in the following JSON format with NO extra comments. The JSON schema is as follows: ' +
		JSON.stringify(Schema) +
		' term and term2 (if present) should ONLY contain single field names from the sqlite db — never comma-separated values, never category values like subtype names. ' +
		'When the user says "across [field]" or "by [field]" (e.g. "across molecular subtypes", "by sex"), that field should be term2 — it is the grouping/overlay variable. ' +
		'When the user mentions specific category VALUES by name (e.g. "between KMT2A and DUX4", "in male patients"), put those values in "simpleFilter" to restrict the data. ' +
		'A query can have BOTH: e.g. "Vincristine sensitivity in male patients across molecular subtypes" → term=Vincristine sensitivity, term2=molecular subtype field, simpleFilter=[sex=male]. ' +
		buildCommonPrompt({
			ds,
			dataset_json,
			chart_ds: summary_ds,
			dataset_db_output,
			training_data,
			common_genes,
			prompt,
			termFieldNames: ['term', 'term2'],
			matchedGenesets
		})

	const response: string = await route_to_appropriate_llm_provider(system_prompt, llm)
	if (testing) {
		// When testing, send raw LLM response
		const test_response = JSON.parse(response)
		test_response.plot = 'summary'
		test_response.type = 'plot'
		return test_response
	} else {
		// In actual production (inside PP) send LLM output for validation
		return validate_summary_response(response, ds, geneFeatures)
	}
}

function extract_term_name(
	tw: term,
	ds: any,
	geneFeatures: GeneDataTypeResult[]
): {
	term_type?: { id: string } | { term: { gene: string; type: 'geneExpression' } }
	text: string
	category?: string
} {
	const termObj = tw
	let text = ''
	let term_type: { id: string }
	let category: string = ''
	console.log('Extracting term name from termwrapper:', tw)
	if ('dictionaryTerm' in termObj) {
		// Dictionary term
		const term =
			ds.cohort.termdb.q.termjsonByOneid(termObj.dictionaryTerm) ||
			ds.cohort.termdb.q.termjsonByOneid(termObj.dictionaryTerm.toUpperCase()) ||
			ds.cohort.termdb.q.termjsonByOneid(termObj.dictionaryTerm.toLowerCase())
		if (!term) {
			text += 'Dictionary term ' + termObj.dictionaryTerm + ' not found in dataset. '
			return { text: text }
		}
		term_type = { id: term.id }
		category = term.type
		return { term_type: term_type, category: category, text: text }
	} else if ('gene' in termObj) {
		// Non dictionary gene term
		if (termObj.dataType == 'geneExp') {
			if (!ds?.queries?.geneExpression) {
				text += 'Dataset does not support gene expression'
				return { text: text }
			}
			const gene_hit = geneFeatures.find(geneTerm => geneTerm.gene.toLowerCase() == termObj.gene.toLowerCase())
			if (!gene_hit) {
				text += 'Gene name not found:' + termObj.gene
				return { text: text }
			} else {
				//if (gene_hit.dataType == 'expression') {
				const term_type = { term: { gene: gene_hit.gene.toUpperCase(), type: 'geneExpression' as const } }
				return { term_type: term_type, text: text, category: 'float' }
				//}
			}
		} else if (termObj.dataType == 'variant' || termObj.dataType == 'methylation' || termObj.dataType == 'proteome') {
			text += 'Gene data type ' + termObj.dataType + ' is not supported currently'
			return { text: text }
		} else {
			text += 'Unknown gene data type: ' + termObj.dataType
			return { text: text }
		}
	} else if ('chr' in termObj) {
		// Non dictionary coordinate term
		return { text: 'Coordinate terms are not currently supported' }
	} else if ('metabolite' in termObj) {
		// Non dictionary metabolite term
		return { text: 'Metabolite terms are not currently supported' }
	} else {
		return { text: 'Unknown term type' }
	}
}

function validate_summary_response(response: string, ds: any, geneFeatures: GeneDataTypeResult[]) {
	const response_type = JSON.parse(response)
	console.log('Validating summary response:', response_type)
	const pp_plot_json: any = { chartType: 'summary' }
	let text = ''
	if (response_type.text) text = response_type.text
	if (!response_type.term) {
		text += 'term type is not present in summary output'
		return { type: 'text', text: text }
	}
	const term1_validation = extract_term_name(response_type.term, ds, geneFeatures)
	if (term1_validation?.text?.length > 0) {
		text += term1_validation.text
		return { type: 'text', text: text }
	} else {
		pp_plot_json.term = term1_validation.term_type
		if (term1_validation.category == 'float' || term1_validation.category == 'integer') {
			pp_plot_json.term.q = { mode: 'continuous' }
		}
		pp_plot_json.category = term1_validation.category
	}

	if (response_type.term2) {
		const term2_validation = extract_term_name(response_type.term2, ds, geneFeatures)
		if (term2_validation.text.length > 0) {
			text += term2_validation.text
			return { type: 'text', text: text }
		} else {
			pp_plot_json.term2 = term2_validation.term_type
			if (term2_validation.category == 'float' || term2_validation.category == 'integer') {
				pp_plot_json.term2.q = { mode: 'continuous' }
			}
			pp_plot_json.category2 = term2_validation.category
		}
	}

	if (response_type.term0) {
		const term0_validation = extract_term_name(response_type.term0, ds, geneFeatures)
		if (term0_validation.text.length > 0) {
			text += term0_validation.text
			return { type: 'text', text: text }
		} else {
			pp_plot_json.term0 = term0_validation.term_type
			if (term0_validation.category == 'float' || term0_validation.category == 'integer') {
				pp_plot_json.term0.q = { mode: 'continuous' }
			}
		}
	}
	/** Based on data types of term and term2, decide the most appropriate chart type.
	 *  The user can override the default by explicitly mentioning a chart type in their prompt,
	 *  which the LLM parses into the "childType" field. Invalid overrides produce an error. */
	const llmChildType =
		response_type.childType && ['violin', 'boxplot', 'sampleScatter', 'barchart'].includes(response_type.childType)
			? response_type.childType
			: undefined
	const resolved = resolveChildType(pp_plot_json.category, pp_plot_json.category2, llmChildType)

	if (resolved.error) {
		text += resolved.error
		return { type: 'text', text: text }
	} else {
		pp_plot_json.childType = resolved.childType
		// For two numeric variables displayed as violin/boxplot, discretize term2
		if (pp_plot_json.childType == 'barchart') {
			pp_plot_json.term.q = { mode: 'discrete' }
			if (pp_plot_json.term2) {
				pp_plot_json.term2.q = { mode: 'discrete' }
			}
		}
		if (resolved.bothNumeric && (resolved.childType == 'violin' || resolved.childType == 'boxplot')) {
			pp_plot_json.term2.q = { mode: 'discrete' }
		}
	}

	delete pp_plot_json.category
	if (pp_plot_json.category2) delete pp_plot_json.category2

	if (response_type.simpleFilter && response_type.simpleFilter.length > 0) {
		const validated_filters = validate_filter(response_type.simpleFilter, ds, '')
		if (validated_filters.text.length > 0) {
			text += validated_filters.text
			return { type: 'text', text: text }
		} else {
			pp_plot_json.filter = validated_filters.simplefilter
		}
	}
	console.log('Validated summary plot JSON pp_plot_json:', pp_plot_json)
	return { type: 'plot', plot: pp_plot_json }
}

function resolveChildType(
	cat1: TermCategory,
	cat2: TermCategory,
	llmChildType: string | undefined
): { childType?: string; error?: string; bothNumeric?: boolean } {
	const norm1 = cat1 == 'float' || cat1 == 'integer' ? 'numeric' : cat1 || 'undefined'
	const norm2 = cat2 == 'float' || cat2 == 'integer' ? 'numeric' : cat2 || 'undefined'
	const key = norm1 + ':' + norm2
	const defaultType = CHILD_TYPE_DEFAULTS[key]
	if (!defaultType) {
		// Unknown category combination — should not happen, fall back to barchart
		return { childType: 'barchart' }
	}
	const invalid = CHILD_TYPE_INVALID[key]

	if (llmChildType && invalid && invalid.has(llmChildType)) {
		return {
			error:
				'Invalid plot type supplied by the user: ' +
				llmChildType +
				'. For ' +
				key.replace(':', ' and ') +
				' variables the plot type should always be ' +
				defaultType
		}
	}

	return {
		childType: llmChildType || defaultType,
		bothNumeric: norm1 == 'numeric' && norm2 == 'numeric'
	}
}
