apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: protein-paint-pvc
  labels:
    {{- include "protein-paint.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1200Gi
  volumeName: protein-paint-pv
