"""
diffSpliceScreen.py -- genome-wide differential splicing screen for the volcano.

    run_python('diffSpliceScreen.py', JSON.stringify(req))

edgeR::diffSpliceDGE over every testable cluster; ~20 s genome-wide on a 186-sample
cohort. Never imports torch or pyro -- the screen fits no model, and those cost ~1.9 s of
the request. Use diffSpliceRun.py to drill into a hit with the exact test.

REQUEST
    {
      "h5":       "/path/cohort.h5",            required
      "group1":   ["s1", ...],                  required -- the CONTROL group
      "group2":   ["s3", ...],                  required -- the CASE group
      "covariates": {"s1": {"batch": "A"}, ...} default null (a path also works)
      "min_coverage":           20,
      "min_samples_per_intron":  5,             an absolute count: raise it on large
      "min_samples_per_group":   3,             cohorts or it silently loosens
      "max_cluster_size":     null,             null = no cap
      "threads":                 8,             clamped to available CPUs and to
                                                clusters/2000, so a smaller box or cohort
                                                silently uses fewer
      "top":                  null              keep only the N best-ranked clusters
    }

RESPONSE
    { "ok": true, "cluster_data": [DiffSpliceEntry...],
      "num_controls": N, "num_cases": M, "skipped": {},
      "n_clusters_tested": 20906, "n_significant_fdr05": 7508, "truncated": false }

`skipped` is empty here by construction: the screen tests every cluster that survives
filtering and reports no per-cluster status. diffSpliceRun.py fills it.

The screen ranks, it does not adjudicate -- an FDR cutoff here hides clusters the exact
test would call significant. `delta_psi` is descriptive (mean of per-sample PSI), which
is what the x axis wants; only diffSpliceRun.py accounts for overdispersion.
"""
# Generated by build_portal_scripts.py from the leafcutter-ds source tree.
# Do not edit here -- edit portal_screen.py / the engine modules and regenerate.

import warnings

warnings.filterwarnings("ignore")

import json
import os
import sys

# Cap BLAS/OpenMP threads BEFORE numpy loads: these pools are sized at import time, so
# setting them afterwards is a no-op. Without the cap every worker process starts its own
# multi-threaded BLAS and they oversubscribe the machine, making a larger thread count
# SLOWER than a small one.
for _v in ("OMP_NUM_THREADS", "OPENBLAS_NUM_THREADS", "MKL_NUM_THREADS",
           "BLIS_NUM_THREADS", "NUMEXPR_NUM_THREADS", "VECLIB_MAXIMUM_THREADS"):
    os.environ.setdefault(_v, "1")

# Everything below is guarded. A missing dependency has to come back as a JSON body:
# run_python discards the response on a non-zero exit and rejects on any stderr, so an
# unguarded ImportError reaches the route as an opaque failure instead of naming the
# module. The engine definitions that follow use numpy and torch at class-definition
# time, so the guard wraps the imports rather than deferring them.
try:
    import argparse
    import contextlib
    import tempfile
    import traceback
    from collections import Counter
    from timeit import default_timer as timer

    import numpy as np
    import pandas as pd

except Exception as _import_error:
    json.dump({"ok": False,
               "error": f"{type(_import_error).__name__}: {_import_error}",
               "error_type": "environment",
               "cluster_data": [], "num_controls": 0, "num_cases": 0, "skipped": {}},
              sys.stdout)
    sys.stdout.write("\n")
    raise SystemExit(0)


def get_intron_meta(introns):
    """ Make a data.frame of meta data about the introns
    
    introns Names of the introns
    Returns: Data.frame with chr, start, end, cluster_name
    """
    intron_meta = pd.Series(introns).str.split(":", expand = True)
    if intron_meta.shape[1] == 4:
        intron_meta.columns = ['chr', 'start', 'end', 'cluster']
    elif intron_meta.shape[1] == 5:
        intron_meta.columns = ['chr', 'start', 'end', 'cluster', 'annotation']
    return intron_meta

def _load_into_memory(path):
    """
    Reopen a store with HDF5's in-memory driver, so every later read is served from this
    process's own RAM.

    On a shared filesystem a strided read costs far more than reading everything: measured on
    GPFS for a 0.92 GB / 2525-sample cohort, `cat` ran at 42-85 MB/s while h5py's 186
    per-sample reads of the 67 MB actually wanted took 235 s. Warming the OS page cache first
    was not enough -- 0.92 GB did not stay resident, and the reads still spent ~33 s waiting.
    Holding the image in the process removes the dependency on the page cache entirely; it
    costs one sequential pass plus `size` bytes of RAM.
    """
    import h5py
    return h5py.File(path, "r", driver="core", backing_store=False)

def read_h5_samples(h5_path, sample_names, row_ranges=None, prefetch="auto"):
    """
    Read the given samples out of the HDF5 store.

    Returns (buf, intron_ids, cluster_ids, cluster_starts) where buf is [samples x introns].
    Samples are read one row at a time: handing h5py a list of indices instead builds a
    union of hyperslabs and is dramatically slower for the same bytes (measured 0.4s vs 3.9s
    on a 927k x 200 store).
    """
    import h5py
    with h5py.File(h5_path, "r") as f:
        stored = [s.decode() if isinstance(s, bytes) else str(s) for s in f["samples"][:]]
        pos = {s: i for i, s in enumerate(stored)}
        missing = [s for s in sample_names if s not in pos]
        if missing:
            raise KeyError(f"{len(missing)} sample(s) not in {h5_path}, e.g. {missing[:5]}")
        cols = [pos[s] for s in sample_names]

        d = f["X"]
        # files built before the layout attribute existed are introns x samples
        layout = f.attrs.get("layout", "introns_x_samples")
        if isinstance(layout, bytes):
            layout = layout.decode()
        transposed = (layout == "samples_x_introns")
        n_all = d.shape[1] if transposed else d.shape[0]
        n_all_samples = d.shape[0] if transposed else d.shape[1]

        if row_ranges is None:
            keep = None
            n_introns = n_all
        else:
            # only the introns of the requested clusters -- makes gene drill-down sub-second
            keep = np.concatenate([np.arange(a, b) for a, b in row_ranges])
            n_introns = len(keep)

        # A sample's chunks are adjacent on disk but different samples are not, so 186 of
        # 2525 samples means 186 reads scattered over the file. They cost the same bytes in
        # any order, but issuing them in increasing sample index walks the file forwards,
        # which is the only pattern a shared filesystem's readahead can help with.
        read_order = np.argsort(cols, kind="stable")

        size = os.path.getsize(h5_path)
        if prefetch == "auto":
            # Skip it for the metadata-only calls, for stores too big to hold in RAM
            # alongside the result, and when nearly every sample is wanted (the loop below is
            # then already one forward pass). Note this does NOT depend on row_ranges: the
            # reads below pull whole sample rows either way, so a --gene or --chrom subset
            # pays exactly the same scattered-read cost that the load is there to avoid.
            prefetch = (len(cols) >= 8 and size <= 8e9
                        and len(cols) < 0.8 * n_all_samples)
        mem = None
        if prefetch:
            t_pf = timer()
            mem = _load_into_memory(h5_path)
            d = mem["X"]
            print(f"  loaded {size/1e9:.2f} GB into memory ({len(cols)} of {n_all_samples} "
                  f"samples wanted, so reading in place would be scattered) "
                  f"[{timer()-t_pf:.1f}s]")

        buf = np.empty((len(cols), n_introns), dtype=d.dtype)
        # Legacy introns x samples stores put a sample's chunks n_samples chunks apart, so a
        # per-sample d[:, j] is one scattered read per chunk per sample. Reading whole
        # chunk-row blocks instead makes every read sequential -- but it decompresses ALL
        # n_samples columns, so it only pays when the caller wants most of them. On a
        # 2525-sample cohort asked for 186 samples that is a 13.6x amplification, and it
        # measured 3x SLOWER on GPFS than the scattered reads (414s vs 132s). Rebuilding
        # with `build` is what actually fixes such a file.
        if not transposed:
            print(f"  note: {os.path.basename(h5_path)} has the legacy introns x samples "
                  f"layout; rebuild it with `build` to make each sample contiguous on disk")
        if transposed:
            # each sample is one contiguous run of chunks: read it in one go
            for k in read_order:
                col = d[cols[k], :]
                buf[k, :] = col if keep is None else col[keep]
        elif keep is None and d.shape[1] / max(1, len(cols)) <= 3:
            cr = d.chunks[0] if d.chunks else max(1, 2 ** 18)
            per_read = max(1, int(2e9 // max(1, cr * d.shape[1] * d.dtype.itemsize)))
            step = cr * per_read
            take = np.asarray(cols)
            for i0 in range(0, n_introns, step):
                i1 = min(i0 + step, n_introns)
                buf[:, i0:i1] = d[i0:i1, :][:, take].T
        else:
            # few enough samples (or few enough introns, on a gene drill-down) that paying
            # the seeks beats decompressing everything
            for k in read_order:
                col = d[:, cols[k]]
                buf[k, :] = col if keep is None else col[keep]

        if mem is not None:
            mem.close()

        all_ids = np.array([s.decode() if isinstance(s, bytes) else str(s)
                            for s in f["intron_ids"][:]])
        intron_ids = all_ids if keep is None else all_ids[keep]
        cluster_ids = np.array([s.decode() if isinstance(s, bytes) else str(s)
                                for s in f["cluster_ids"][:]])
        cluster_starts = f["cluster_starts"][:]
        if "cluster_genes" in f:
            cluster_genes = np.array([s.decode() if isinstance(s, bytes) else str(s)
                                      for s in f["cluster_genes"][:]])
        else:
            cluster_genes = np.array([""] * len(cluster_ids))
    return buf, intron_ids, cluster_ids, cluster_starts, cluster_genes

def _available_cpus():
    """CPUs this process may actually use -- respects SLURM/cgroup affinity, unlike cpu_count()."""
    try:
        return len(os.sched_getaffinity(0))   # Linux
    except AttributeError:
        return os.cpu_count() or 1

def _read_sample_list(path):
    """A path to a one-name-per-line file, or an already-materialised list of names."""
    if isinstance(path, (list, tuple)):
        names = [str(s).split()[0] for s in path if str(s).strip()]
    else:
        with open(path) as f:
            names = [ln.split()[0] for ln in f
                     if ln.strip() and not ln.lstrip().startswith('#')]
    if not names:
        raise ValueError(f"{path} contains no sample names")
    dup = [s for s, n in Counter(names).items() if n > 1]
    if dup:
        raise ValueError(f"{path} lists duplicate samples: {dup[:5]}")
    return names

def _encode_covariates(path, samples):
    """Whitespace-delimited, no header: column 0 is the sample name, the rest are covariates.
    Numeric columns are standardized, non-numeric are one-hot encoded (first level dropped)."""
    from sklearn.preprocessing import StandardScaler, OneHotEncoder
    from sklearn.compose import ColumnTransformer

    def _onehot():
        # sklearn renamed this keyword in 1.2 (sparse -> sparse_output)
        try:
            return OneHotEncoder(drop='first', sparse_output=False)
        except TypeError:
            return OneHotEncoder(drop='first', sparse=False)

    if isinstance(path, dict):
        # {sample: {name: value}} or {sample: [values]} -- the shape a portal has on hand
        cov = pd.DataFrame.from_dict(path, orient="index")
    else:
        cov = pd.read_table(path, header=None, sep=r'\s+')
        cov = cov.set_index(cov.columns[0])
    cov.columns = [str(c) for c in cov.columns]
    missing = [s for s in samples if s not in cov.index]
    if missing:
        raise KeyError(f"{len(missing)} sample(s) missing from {path}, e.g. {missing[:5]}")
    cov = cov.loc[samples]

    transformations = []
    for col in cov.columns:
        if pd.api.types.is_numeric_dtype(cov[col]):
            transformations.append((col, StandardScaler(), [col]))
        else:
            transformations.append((col, _onehot(), [col]))
    out = ColumnTransformer(transformations).fit_transform(cov)
    out = pd.DataFrame(out).reset_index(drop=True)  # positional, aligned with `samples`
    if out.isna().any().any():
        raise ValueError(f"{path} has missing values for the selected samples")
    return out

# Run through R rather than reimplemented in Python: diffSpliceDGE depends on edgeR's
# Cox-Reid dispersion estimation and empirical-Bayes moderation, and an approximate
# reimplementation would diverge silently. Counts are handed over as a raw int32 blob --
# writing a 1M x 200 TSV would take longer than the analysis itself.
_EDGER_R = r"""
suppressMessages(library(edgeR))
a <- commandArgs(trailingOnly=TRUE)
bin_file <- a[1]; meta_file <- a[2]; design_file <- a[3]; out_file <- a[4]
n_introns <- as.integer(a[5]); n_samples <- as.integer(a[6])
n_threads <- as.integer(a[7])

v <- readBin(bin_file, what="integer", n=n_introns*n_samples, size=4L)
# Python writes its [samples x introns] buffer C-contiguous, which is byte-for-byte R's
# column-major [introns x samples] -- so neither side needs a transpose.
M <- matrix(v, nrow=n_introns, ncol=n_samples)
meta <- read.table(meta_file, header=TRUE, sep="\t", stringsAsFactors=FALSE,
                   quote="", comment.char="")
design <- as.matrix(read.table(design_file, header=TRUE, sep="\t"))
rownames(M) <- meta$intron

y <- DGEList(counts=M, genes=data.frame(GeneID=meta$cluster, ExonID=meta$intron,
                                        chr=meta$chr, stringsAsFactors=FALSE))
# TMM pins down one scalar per sample, so it does not need every intron. On a
# 104k x 186 matrix the full call costs ~16s and an evenly spaced 30k-row subset ~3s;
# the factors agree to <0.1, which the within-cluster contrast largely absorbs anyway.
# The stride is deterministic, so repeat runs give identical output.
TMM_SUBSET <- 30000L
if (n_introns > TMM_SUBSET) {
  idx <- unique(as.integer(seq.int(1, n_introns, length.out=TMM_SUBSET)))
  y$samples$norm.factors <- calcNormFactors(y$counts[idx, , drop=FALSE],
                                            lib.size=y$samples$lib.size)
} else {
  y <- calcNormFactors(y)
}

edger4 <- packageVersion("edgeR") >= "4.0.0"

fit_block <- function(rows) {
  yy <- y[rows, ]        # lib.size and norm.factors stay those of the whole matrix
  if (edger4) {
    # edgeR >= 4 estimates the quasi-dispersion inside glmQLFit (legacy=FALSE, the default)
    # and never reads the tagwise dispersions estimateDisp produces, so running it is pure
    # cost -- ~38s of the ~66s R stage on a 104k x 186 matrix. Dropping it leaves the
    # ranking intact (Spearman 0.9995 on -log10 p, 990/1000 top-cluster overlap).
    f <- glmQLFit(yy, design, robust=TRUE, legacy=FALSE)
  } else {
    yy <- estimateDisp(yy, design, robust=TRUE)
    f <- glmQLFit(yy, design, robust=TRUE)
  }
  ds <- diffSpliceDGE(f, coef=ncol(design), geneid="GeneID", exonid="ExonID", verbose=FALSE)
  t <- topSpliceDGE(ds, test="Simes", n=Inf)
  data.frame(cluster=t$GeneID, chr=t$chr, n_junc=t$NExons, p=t$P.Value,
             stringsAsFactors=FALSE)
}

# Splitting the fit across cores is worth doing (11.6s -> 3.2s on 4 cores for a
# 87k x 186 matrix) but it is not free: glmQLFit's empirical-Bayes variance moderation
# borrows strength ACROSS rows, so each block gets its own prior. Measured against the
# single-block fit that costs almost nothing at these block sizes -- Spearman 1.000000
# at 4 blocks, 0.999999 at 8, identical FDR<0.05 sets, max |dp| 4.7e-3 -- but the blocks
# must stay large, which is why the thread count is capped rather than scaled up freely.
if (n_threads > 1) {
  # clusters occupy contiguous row ranges (the h5 stores introns sorted by cluster and the
  # filter preserves that order), so cutting on cluster boundaries keeps every cluster whole
  ends <- cumsum(rle(meta$cluster)$lengths)
  targets <- seq_len(n_threads - 1L) * (n_introns / n_threads)
  cuts <- unique(c(0L, ends[pmin(findInterval(targets, ends) + 1L, length(ends))], n_introns))
  blocks <- lapply(seq_len(length(cuts) - 1L), function(k) (cuts[k] + 1L):cuts[k + 1L])
  parts <- parallel::mclapply(blocks, fit_block, mc.cores=min(n_threads, length(blocks)))
  bad <- !vapply(parts, is.data.frame, logical(1))
  if (any(bad)) stop("block ", which(bad)[1], " failed: ", parts[[which(bad)[1]]])
  res <- do.call(rbind, parts)
} else {
  res <- fit_block(seq_len(n_introns))
}

# BH over every cluster, not per block -- this is what topSpliceDGE does internally, so
# the single- and multi-block paths adjust identically.
res$fdr <- p.adjust(res$p, method="BH")
res <- res[order(res$p), ]
write.table(res, out_file, sep="\t", quote=FALSE, row.names=FALSE)
cat(sprintf("edgeR: %d clusters tested, %d at FDR<0.05%s\n", nrow(res), sum(res$fdr < 0.05),
            if (n_threads > 1) sprintf(" [%d blocks]", length(blocks)) else ""))
"""

def group_mean_psi(sub, widths, n1, block=2048):
    """Group-mean PSI per intron, straight from the counts -- no model.

    PSI is a within-cluster proportion, so its denominator is the sum over the introns the
    cluster actually KEPT; an intron dropped by the filter must leave the denominator too,
    or every PSI in that cluster is wrong. Samples with no coverage in a cluster contribute
    nothing to that cluster, matching the rule the fit uses.

    Averaging is mean-of-ratios (every sample counts once), not pooled sums. Checked
    against `run`'s model-based deltapsi on a 1972-sample cohort: mean-of-ratios reaches
    Pearson 0.94 / Spearman 0.93 where the depth-weighted pooled version manages 0.78, and
    the sign agrees on 100% of introns once |deltapsi| >= 0.05.

    `sub` is [samples x kept introns], `widths` the kept intron count per cluster in order.
    The ratio matrix is built a block of clusters at a time: materialising it whole would
    be 3.4 GB on a 2000-sample, 210k-intron screen.
    """
    I = sub.shape[1]
    bounds = np.concatenate([[0], np.cumsum(widths)]).astype(np.int64)
    g1m = np.full(I, np.nan)
    g2m = np.full(I, np.nan)
    C = len(widths)
    for c0 in range(0, C, block):
        c1 = min(C, c0 + block)
        s0, s1 = int(bounds[c0]), int(bounds[c1])
        y = sub[:, s0:s1].astype(np.float32)
        w = widths[c0:c1]
        tot = np.repeat(np.add.reduceat(y, bounds[c0:c1] - s0, axis=1), w, axis=1)
        ok = tot > 0
        r = np.where(ok, y / np.where(tot == 0, 1, tot), 0.0)
        for dst, sl in ((g1m, slice(0, n1)), (g2m, slice(n1, None))):
            n = ok[sl].sum(0)
            np.divide(r[sl].sum(0), n, out=dst[s0:s1], where=n > 0)
    return g1m, g2m

def leafcutter_cluster_filter(buf, cluster_starts, n_group1, min_coverage=20,
                              min_samples_per_intron=5, min_samples_per_group=3,
                              max_cluster_size=float('inf')):
    """
    Vectorised version of the per-cluster filters in task(), so the screen tests the same
    cluster set leafcutter would.

    This is about power, not just consistency. leafcutter typically tests ~7% of clusters;
    screening all of them makes the BH threshold at a given rank ~15x stricter, which costs
    real sensitivity on the clusters that do carry signal. It also stops the screen from
    surfacing clusters the drill-down would refuse to test.

    Returns (keep_introns, keep_clusters) boolean masks.
    """
    starts = cluster_starts[:-1]
    sizes = np.diff(cluster_starts)
    # task() checks max_cluster_size FIRST, against the raw intron count -- before any
    # coverage or per-intron filtering -- so it is applied to `sizes`, not to the survivors.
    ok_size = (sizes >= 2) & (sizes <= max_cluster_size)
    tot = np.add.reduceat(buf, starts, axis=1)              # [samples x clusters]
    # task() discards zero-coverage samples FIRST and applies min_coverage to what is
    # left, so a sample with no reads in this cluster must not count toward
    # min_samples_per_group. Testing `tot >= min_coverage` against every sample agrees
    # with that for any positive threshold but not at min_coverage = 0, where it is true
    # for the very samples the per-cluster path has already dropped.
    covered = (tot > 0) & (tot >= min_coverage)
    ok_cov = ((tot > 0).sum(0) > 1) & (covered.sum(0) > 1)
    ok_grp = ((covered[:n_group1].sum(0) >= min_samples_per_group)
              & (covered[n_group1:].sum(0) >= min_samples_per_group))
    # an intron carrying any read necessarily has a non-zero cluster total, so restricting
    # to samples_to_use never changes which introns qualify
    intron_ok = (buf > 0).sum(0) >= min_samples_per_intron
    n_int_ok = np.add.reduceat(intron_ok.astype(np.int64), starts)
    keep_clusters = ok_size & ok_cov & ok_grp & (n_int_ok >= 2)
    keep_introns = intron_ok & np.repeat(keep_clusters, np.diff(cluster_starts))
    return keep_introns, keep_clusters

def cmd_screen(args, return_data=False):
    import shutil
    import subprocess
    import tempfile

    t0 = timer()
    rscript = shutil.which("Rscript")
    if rscript is None:
        raise RuntimeError(
            "Rscript not found. The screen uses edgeR::diffSpliceDGE.\n"
            "  Install R, then:  Rscript -e 'BiocManager::install(\"edgeR\")'\n"
            "  (`run --genome-wide` needs no R, but takes minutes rather than seconds.)")

    g1 = _read_sample_list(args.group1)
    g2 = _read_sample_list(args.group2)
    both = set(g1) & set(g2)
    if both:
        raise ValueError(f"{len(both)} sample(s) in both groups, e.g. {sorted(both)[:5]}")
    samples = g1 + g2
    print(f"Group '{args.name1}': {len(g1)} samples;  group '{args.name2}': {len(g2)} samples")

    buf, intron_ids, cluster_ids, cluster_starts, cluster_genes = read_h5_samples(
        args.h5, samples, prefetch=(False if args.no_prefetch else "auto"))
    print(f"  {buf.shape[1]} introns, {len(cluster_ids)} clusters  [{timer()-t0:.1f}s]")

    if args.no_leafcutter_filter:
        nz = buf.sum(0) > 0
        n_nz = np.add.reduceat(nz.astype(np.int64), cluster_starts[:-1])
        keep_clu = n_nz >= 2
        keep = nz & np.repeat(keep_clu, np.diff(cluster_starts))
        print("  --no-leafcutter-filter: screening every cluster with >=2 non-empty junctions")
    else:
        keep, keep_clu = leafcutter_cluster_filter(
            buf, cluster_starts, len(g1), min_coverage=args.min_coverage,
            min_samples_per_intron=args.min_samples_per_intron,
            min_samples_per_group=args.min_samples_per_group,
            max_cluster_size=args.max_cluster_size)
    print(f"  after filtering: {int(keep.sum())} introns in {int(keep_clu.sum())} clusters "
          f"(of {len(cluster_ids)})")
    if keep.sum() == 0:
        raise ValueError("nothing left to screen after filtering")

    clu_of_intron = np.repeat(cluster_ids, np.diff(cluster_starts))
    sub = buf[:, keep]
    chrom = np.array([i.split(':')[0] for i in intron_ids[keep]])

    # design: covariates first, group LAST, so the group coefficient is the final column
    cols = {"intercept": np.ones(len(samples))}
    if args.covariates:
        cov = _encode_covariates(args.covariates, samples)
        for j, c in enumerate(cov.columns):
            cols[f"cov{j+1}"] = cov[c].to_numpy(dtype=float)
        print(f"  design includes {cov.shape[1]} covariate column(s)")
    cols["grp"] = np.array([0.0] * len(g1) + [1.0] * len(g2))
    design = pd.DataFrame(cols)

    tmp = tempfile.mkdtemp(prefix="lcds_screen_")
    try:
        binf = os.path.join(tmp, "counts.bin")
        np.ascontiguousarray(sub, dtype=np.int32).tofile(binf)
        pd.DataFrame({"intron": intron_ids[keep], "cluster": clu_of_intron[keep],
                      "chr": chrom}).to_csv(os.path.join(tmp, "meta.tsv"),
                                            sep="\t", index=False)
        design.to_csv(os.path.join(tmp, "design.tsv"), sep="\t", index=False)
        rfile = os.path.join(tmp, "edger.R")
        with open(rfile, "w") as fh:
            fh.write(_EDGER_R)
        outf = os.path.join(tmp, "out.tsv")

        nthr = max(1, int(args.num_threads))
        avail = _available_cpus()
        if nthr > avail:
            print(f"  --threads {nthr} exceeds the {avail} CPU(s) available; using {avail}")
            nthr = avail
        # Blocks must stay large enough for the empirical-Bayes moderation inside each one
        # to be well determined; below ~2000 clusters per block the priors start to drift.
        max_by_size = max(1, int(keep_clu.sum()) // 2000)
        if nthr > max_by_size:
            print(f"  only {int(keep_clu.sum())} clusters to test; using {max_by_size} thread(s) "
                  f"to keep each block large enough for the variance moderation")
            nthr = max_by_size

        print(f"Running edgeR diffSpliceDGE{f' on {nthr} threads' if nthr > 1 else ''}...")
        t_r = timer()
        # edgeR fits one small GLM per intron, so a threaded BLAS buys nothing (measured:
        # 11.6s on 1 BLAS thread vs 11.7s on 8) and only risks oversubscribing the cores
        # mclapply is already using. Leave an explicit user setting alone.
        env = dict(os.environ)
        for v in ("OMP_NUM_THREADS", "OPENBLAS_NUM_THREADS", "MKL_NUM_THREADS",
                  "VECLIB_MAXIMUM_THREADS"):
            env.setdefault(v, "1")
        res = subprocess.run(
            [rscript, "--vanilla", rfile, binf, os.path.join(tmp, "meta.tsv"),
             os.path.join(tmp, "design.tsv"), outf, str(sub.shape[1]), str(sub.shape[0]),
             str(nthr)],
            capture_output=True, text=True, env=env)
        if res.returncode != 0:
            raise RuntimeError("edgeR failed:\n" + (res.stderr or res.stdout)[-2000:])
        print("  " + res.stdout.strip().replace("\n", "\n  ") + f"  [{timer()-t_r:.1f}s]")
        out = pd.read_table(outf)
    finally:
        import shutil as _sh
        _sh.rmtree(tmp, ignore_errors=True)

    # Effect size for the volcano's x axis. diffSpliceDGE reports only evidence, but
    # deltaPSI needs no model at all -- it is a descriptive property of the counts, which
    # are already in memory. Reported per cluster as the signed deltaPSI of its largest
    # |deltaPSI| intron, the junction that carries the cluster's shift.
    widths = np.add.reduceat(keep.astype(np.int64), cluster_starts[:-1])
    kept_clu = cluster_ids[widths > 0]
    widths = widths[widths > 0]
    t_ps = timer()
    psi1, psi2 = group_mean_psi(sub, widths, len(g1))
    dpsi = psi2 - psi1
    ci = np.repeat(np.arange(len(widths)), widths)
    order = np.lexsort((-np.abs(np.nan_to_num(dpsi)), ci))
    firsts = np.concatenate([[0], np.flatnonzero(np.diff(ci[order])) + 1])
    top = order[firsts]                      # per cluster, its largest-|deltaPSI| intron
    # Genomic span of each cluster: its introns' leftmost start and rightmost end. The
    # volcano's drill-down opens a violin at chr/start/stop, so it travels with the row.
    km = get_intron_meta(intron_ids[keep])
    ci_s = pd.Series(np.repeat(np.arange(len(widths)), widths))
    span = pd.DataFrame({"chr": km["chr"].to_numpy(),
                         "start": km["start"].astype(np.int64).to_numpy(),
                         "stop": km["end"].astype(np.int64).to_numpy()}).groupby(ci_s).agg(
        {"chr": "first", "start": "min", "stop": "max"})

    eff = pd.DataFrame({"cluster": kept_clu,
                        "chr_": span["chr"].to_numpy(),
                        "start": span["start"].to_numpy(),
                        "stop": span["stop"].to_numpy(),
                        "deltapsi": dpsi[top],
                        "top_intron": intron_ids[keep][top],
                        f"psi_{args.name1}": psi1[top],
                        f"psi_{args.name2}": psi2[top]})
    out = out.merge(eff, on="cluster", how="left")
    print(f"  effect sizes from counts [{timer()-t_ps:.1f}s]")

    gene_of = dict(zip(cluster_ids, cluster_genes))
    out.insert(1, "genes", [gene_of.get(c, "") or np.nan for c in out.cluster])
    out["cluster"] = out["chr"] + ":" + out["cluster"]
    out = out.drop(columns=["chr"]).rename(columns={"chr_": "chr"})
    if return_data:
        return out
    out.to_csv(args.output_prefix + "_screen.txt", sep="\t", index=False, na_rep="NA")
    print(f"Done in {timer()-t0:.1f}s -> {args.output_prefix}_screen.txt")
    print("  Ranked screen. Use the ranking, not an FDR cutoff, to decide what to show:\n"
          "  a cutoff here hides clusters leafcutter would call significant. Drill into a\n"
          "  hit with:  run --gene <GENE>\n"
          "  Volcano: deltapsi on x, -log10(p) on y. deltapsi is descriptive (mean of\n"
          "  per-sample PSI), not the model-based estimate `run` reports -- they track\n"
          "  each other closely but only `run` accounts for overdispersion.")


class _CapturedIO:
    """Swallow everything the pipeline writes while keeping a private channel for the
    response.

    Both fds move, not just stderr: the analysis prints progress to STDOUT, which would
    land in front of the JSON the route parses. fd 1 is duplicated first so the response
    still has somewhere to go, then fd 1 and fd 2 both point at a temp file for the
    duration -- at the descriptor level, so output from R, from spawned workers, and from
    C/C++ below the Python layer is caught too. Those are what would otherwise reach
    run_python and turn a successful run into a rejection.
    """

    def __enter__(self):
        self._buf = tempfile.TemporaryFile(mode="w+b")
        self.response = os.fdopen(os.dup(1), "w")      # the real stdout, kept aside
        self._saved = (os.dup(1), os.dup(2))
        sys.stdout.flush()
        sys.stderr.flush()
        os.dup2(self._buf.fileno(), 1)
        os.dup2(self._buf.fileno(), 2)
        self._py = (sys.stdout, sys.stderr)
        sys.stdout = open(os.devnull, "w")
        sys.stderr = open(os.devnull, "w")
        return self

    def tail(self, limit=4000):
        try:
            self._buf.flush()
            self._buf.seek(0)
            data = self._buf.read().decode("utf-8", "replace").strip()
        except Exception:
            return ""
        return data[-limit:] if len(data) > limit else data

    def __exit__(self, *exc):
        for f in (sys.stdout, sys.stderr):
            try:
                f.close()
            except Exception:
                pass
        sys.stdout, sys.stderr = self._py
        out_fd, err_fd = self._saved
        os.dup2(out_fd, 1)
        os.close(out_fd)
        os.dup2(err_fd, 2)
        os.close(err_fd)
        return False

    def close(self):
        self._buf.close()


def cluster_rows(df, name1, name2, extras=None):
    """Cluster table -> DiffSpliceEntry rows.

    `df` needs cluster, genes, n_junc, p, fdr, deltapsi, top_intron, psi_<name1>,
    psi_<name2>, chr, start, stop. `extras` optionally maps a cluster id to the
    engine-specific `leafcutter` object.
    """
    def num(v, default=None):
        if v is None:
            return default
        try:
            f = float(v)
        except (TypeError, ValueError):
            return default
        return default if not np.isfinite(f) else f

    def txt(v):
        return "" if v is None or (isinstance(v, float) and not np.isfinite(v)) else str(v)

    rows = []
    for r in df.to_dict(orient="records"):
        p = num(r.get("p"))
        fdr = num(r.get("fdr"), p)
        dpsi = num(r.get("deltapsi"), 0.0)
        if p is None:
            continue                       # untested: it belongs in `skipped`, not here
        cid = txt(r.get("cluster"))
        genes = txt(r.get("genes"))
        row = {
            # --- DataEntry ---
            "adjusted_p_value": fdr,
            "original_p_value": p,
            # the volcano's x axis and the unit foldChangeCutoff is read in
            "fold_change": dpsi,
            "gene_id": cid,
            # never empty: getGenesColor throws without it
            "gene_name": genes or cid,
            # --- DiffSpliceEntry ---
            "cluster_id": cid,
            "genes": genes,
            "n_junc": int(num(r.get("n_junc"), 0)),
            "delta_psi": dpsi,
            "top_intron": txt(r.get("top_intron")),
            "psi_control": num(r.get(f"psi_{name1}"), 0.0),
            "psi_case": num(r.get(f"psi_{name2}"), 0.0),
            "chr": txt(r.get("chr")),
            "start": int(num(r.get("start"), 0)),
            "stop": int(num(r.get("stop"), 0)),
        }
        if extras and cid in extras:
            row["leafcutter"] = extras[cid]
        rows.append(row)
    return rows


def main(handler):
    """Read one JSON object from stdin, write one JSON object to stdout, nothing else.

    Always exits 0 with a JSON body: run_python treats a non-zero exit as a hard failure
    and discards the response, so a rejected request has to come back as data.
    """
    cap = _CapturedIO()
    try:
        with cap:
            try:
                raw = sys.__stdin__.read()
                if not raw.strip():
                    raise ValueError("empty request: expected one JSON object on stdin")
                req = json.loads(raw)
                if not isinstance(req, dict):
                    raise ValueError(
                        f"request must be a JSON object, got {type(req).__name__}")
                body = handler(req)
                body.setdefault("ok", True)
            except Exception as e:           # noqa: BLE001 -- this is the boundary
                detail = cap.tail()
                body = {"ok": False,
                        "error": f"{type(e).__name__}: {e}",
                        "traceback": traceback.format_exc()[-4000:],
                        "cluster_data": [], "num_controls": 0, "num_cases": 0,
                        "skipped": {}}
                if detail:
                    body["stderr"] = detail
            out = cap.response
            json.dump(body, out)
            out.write("\n")
            out.flush()
            out.close()
    finally:
        cap.close()
    return 0


def handle(req):
    def field(key, default=None, required=False, cast=None):
        v = req.get(key)
        if v is None:
            if required:
                raise ValueError(f"missing required field: {key!r}")
            return default
        return cast(v) if cast else v

    group1 = field("group1", required=True)
    group2 = field("group2", required=True)
    max_cluster = field("max_cluster_size")
    args = argparse.Namespace(
        h5=field("h5", required=True, cast=str),
        group1=group1,
        group2=group2,
        name1="control",
        name2="case",
        covariates=field("covariates"),
        min_coverage=field("min_coverage", 20, cast=int),
        min_samples_per_intron=field("min_samples_per_intron", 5, cast=int),
        min_samples_per_group=field("min_samples_per_group", 3, cast=int),
        max_cluster_size=float("inf") if max_cluster is None else int(max_cluster),
        num_threads=field("threads", 8, cast=int),
        no_leafcutter_filter=False,
        no_prefetch=False,
        output_prefix=None,
    )
    if args.num_threads < 1:
        raise ValueError("threads must be >= 1")

    out = cmd_screen(args, return_data=True)
    n_tested = len(out)
    n_sig = int((out["fdr"] < 0.05).sum())

    top = field("top", cast=int)
    truncated = bool(top is not None and n_tested > top)
    if truncated:
        out = out.head(top)

    return {
        "cluster_data": cluster_rows(out, "control", "case"),
        "num_controls": len(_read_sample_list(group1)),
        "num_cases": len(_read_sample_list(group2)),
        "skipped": {},
        "n_clusters_tested": n_tested,
        "n_significant_fdr05": n_sig,
        "truncated": truncated,
    }

if __name__ == "__main__":
    raise SystemExit(main(handle))
