# Test syntax: cat ~/sjpp/test.txt | time python gsea.py
# test.txt contains the json string autogenerated by the commented out nodejs code.
import warnings
warnings.filterwarnings("ignore")
import blitzgsea as blitz
import json
import time
import sys
import sqlite3
import os
import base64
import io
import numpy as np
import pandas as pd
from statsmodels.stats.multitest import multipletests

# Helper function to extract gene symbols from a dictionary
def extract_symbols(x):
    return x['symbol']  # Return the 'symbol' field from the dictionary

# Friendly fallback around blitz.gsea(). The library raises ValueError from
# scipy.stats.gamma.fit (via multiprocessing) when its calibration step
# encounters non-finite values — typically when the signature has too few
# genes overlapping the library, or fold-changes that are degenerate (all
# zero / all identical). It also throws ZeroDivisionError on similar
# pathological inputs. Surface a clean structured error to the Node caller
# instead of letting the Python process exit non-zero with a multi-page
# traceback. Returns the gsea result on success, or None after emitting an
# error line — caller should `continue` to the next stdin line.
def _safe_blitz_gsea(signature, library, permutations):
    try:
        return blitz.gsea(signature, library, permutations=permutations)
    except (ValueError, ZeroDivisionError, RuntimeError) as e:
        msg = (
            'GSEA failed: the input signature could not be calibrated by blitzgsea. '
            'This usually means too few genes overlap the selected gene-set library, '
            'or the fold-change values are degenerate (all zero / all identical). '
            f'Underlying error: {type(e).__name__}: {e}'
        )
        # Single-line JSON; the Node side already parses any `result: ` line.
        print(f'result: {json.dumps({"error": msg})}')
        return None

# blitzgsea runs multipletests(pvals, 'fdr_bh') across every gene set, including
# the ones whose p-value came back NaN (its gamma fit does not converge for every
# gene-set size). Benjamini-Hochberg is a whole-array operation -- it sorts, then
# takes a running minimum -- so a single NaN makes every fdr NaN. Measured on a
# 7309-set GO BP run over a GDC cohort: 185 NaN p-values blanked the FDR column
# for all 7309, and FDR is what the table sorts and filters on, so the whole
# result was unusable (354 gene sets are actually below fdr 0.05).
# Recompute over the finite p-values only. A gene set with no p-value was not a
# test and does not belong in the correction's denominator; it keeps NaN and the
# client shows it as blank. Identical to blitzgsea's own output when nothing is
# NaN, so this only ever replaces an all-NaN column.
def _recompute_fdr(res):
    pvals = pd.to_numeric(res['pval'], errors='coerce').to_numpy(dtype=float)
    ok = np.isfinite(pvals)
    if ok.all() or not ok.any():
        return res
    fdr = np.full(len(pvals), np.nan)
    fdr[ok] = multipletests(pvals[ok], method='fdr_bh')[1]
    res['fdr'] = fdr
    # stdout, not stderr: run_python() rejects the whole call if the process writes
    # anything to stderr. The Node side mayLog()s every line that is not `result: `.
    print(f'blitzgsea returned {int((~ok).sum())} of {len(pvals)} gene sets with no p-value; '
          'FDR recomputed over the remaining ones')
    return res

# blitzgsea computes nes as the normal quantile of the permutation p-value, so a
# p-value that underflows its gamma fit comes back as +/-inf: a real "off the
# scale" enrichment, not a missing one (pval is then exactly 0.0 alongside it).
# JSON has no Infinity literal, and pandas' to_json() writes null for inf and NaN
# alike -- which would make "off the scale" indistinguishable from "not computed"
# and leave the client with a blank cell either way. Send the infinities as
# strings so the sign survives; genuine NaN still becomes null.
def _finite_or_label(v):
    return ('Infinity' if v > 0 else '-Infinity') if isinstance(v, float) and np.isinf(v) else v

# Offline check for the two pure helpers above, driven by python/test/gsea.unit.spec.js:
#   echo '/{"selftest":true}' | python python/src/gsea.py
# Neither blitzgsea nor the msigdb sqlite is touched, so this runs anywhere.
# The spelling asserted here is a cross-language contract: client formatStat() in
# plots/gsea/viewModel/GSEAViewModel.ts matches these exact strings, and the
# table's FDR sort/filter relies on JS Number() coercing them, which it only does
# for JS's own spelling ('Infinity'/'-Infinity' -- Number('Inf') is NaN). Changing
# either side alone silently blanks a column, which is what this pins down.
def _selftest():
    labelled = [_finite_or_label(v) for v in
                [float('inf'), float('-inf'), float('nan'), 0.0, -1.5, 3, 'GENE_A']]
    assert labelled[0] == 'Infinity', f'+inf must serialize as Infinity, got {labelled[0]!r}'
    assert labelled[1] == '-Infinity', f'-inf must serialize as -Infinity, got {labelled[1]!r}'
    assert np.isnan(labelled[2]), 'NaN must be left alone so to_json writes null'
    assert labelled[3] == 0.0 and labelled[4] == -1.5, 'finite floats must pass through unchanged'
    assert labelled[5] == 3 and labelled[6] == 'GENE_A', 'non-float cells must pass through unchanged'

    # the wire itself, in the shape gsea.py emits: (fields x gene sets) after .T
    frame = pd.DataFrame({
        'SET_POS': {'nes': float('inf'), 'pval': 0.0, 'fdr': 0.25},
        'SET_NEG': {'nes': float('-inf'), 'pval': 0.0, 'fdr': 0.25},
        'SET_NAN': {'nes': float('nan'), 'pval': float('nan'), 'fdr': float('nan')},
        'SET_OK': {'nes': 1.25, 'pval': 0.01, 'fdr': 0.25},
    }).astype(object)
    wire = json.loads(frame.map(_finite_or_label).to_json())
    assert wire['SET_POS']['nes'] == 'Infinity', wire['SET_POS']
    assert wire['SET_NEG']['nes'] == '-Infinity', wire['SET_NEG']
    assert wire['SET_NAN']['nes'] is None, 'a NaN nes must stay null, distinct from an infinity'
    assert wire['SET_OK']['nes'] == 1.25, wire['SET_OK']

    # one NaN p-value used to make every fdr NaN; the finite ones must survive it
    mixed = pd.DataFrame({'pval': [0.0, 0.01, float('nan'), 0.9]})
    fixed = _recompute_fdr(mixed.copy())['fdr'].to_numpy(dtype=float)
    assert np.isfinite(fixed[[0, 1, 3]]).all(), f'finite p-values must get an fdr, got {fixed}'
    assert np.isnan(fixed[2]), 'a gene set with no p-value keeps no fdr'
    assert (fixed[[0, 1, 3]] <= 1).all() and (fixed[[0, 1, 3]] >= 0).all(), f'fdr out of range: {fixed}'
    # and it must not touch a clean run: blitzgsea's own column is already correct there
    clean = pd.DataFrame({'pval': [0.0, 0.01, 0.9], 'fdr': ['untouched'] * 3})
    assert list(_recompute_fdr(clean.copy())['fdr']) == ['untouched'] * 3, 'clean runs must be left alone'
    return {'selftest': 'ok'}

# Main function
try:
    # Check if there is input from stdin
    if sys.stdin.read(1):
        # Read each line from stdin
        for line in sys.stdin:
            # Parse the JSON input
            json_object = json.loads(line)
            if json_object.get('selftest'):
                try:
                    print(f'result: {json.dumps(_selftest())}')
                except AssertionError as e:
                    print(f'result: {json.dumps({"selftest": "failed", "error": str(e)})}')
                continue
            cachedir = json_object['cachedir']  # Get the cache directory from the JSON object
            genes = json_object['genes']  # Get the genes from the JSON object
            fold_change = json_object['fold_change']  # Get the fold change values from the JSON object
            num_permutations = json_object['num_permutations'] # Number of permutations for GSEA analysis
            table_name = json_object['geneset_group']  # Get the gene set group from the JSON object
            filter_non_coding_genes = json_object['filter_non_coding_genes']  # Get the filter_non_coding_genes flag from the JSON object
            db = json_object['db']  # Get the database path from the JSON object

            # Create a DataFrame for the signature
            df = {'Genes': genes, 'fold_change': fold_change}  # Create a dictionary with genes and fold change
            signature = pd.DataFrame(df)  # Convert the dictionary to a DataFrame

            # Connect to the SQLite database
            conn = sqlite3.connect(db)  # Connect to the SQLite database
            cursor = conn.cursor()  # Create a cursor object

            msigdb_library = {}  # Initialize an empty dictionary for the gene set library
            if table_name == "REACTOME--blitzgsea": # Parse from blitzgsea reactome library
              msigdb_library = blitz.enrichr.get_library("Reactome_2022")
            elif table_name == "KEGG--blitzgsea": # Parse from blitzgsea KEGG library
              msigdb_library = blitz.enrichr.get_library("KEGG_2021_Human")
            elif table_name == "WikiPathways--blitzgsea": # Parse from blitzgsea WikiPathways library
              msigdb_library = blitz.enrichr.get_library("WikiPathways_2019_Human")              
            else: # Use geneset groups from msigdb    
              # Query to get gene set IDs
              query = f"SELECT id FROM terms WHERE parent_id='{table_name}'"  # SQL query to get gene set IDs
              cursor.execute(query)  # Execute the query
              
              # Fetch all gene set IDs
              rows = cursor.fetchall()  # Fetch all rows from the executed query
              
              start_loop_time = time.time()  # Record the start time of the loop
              
              # Iterate over gene set IDs and fetch corresponding genes
              for row in rows:
                  query2 = f"SELECT genes FROM term2genes WHERE id='{row[0]}'"  # SQL query to get genes for a gene set ID
                  cursor.execute(query2)  # Execute the query
                  rows2 = cursor.fetchall()  # Fetch all rows from the executed query
                  row3 = json.loads(rows2[0][0])  # Parse the JSON data
                  msigdb_library[row[0]] = list(set(map(extract_symbols, row3)))  # Extract only unique gene symbols and add them to the library. "set" command selects only unique genes 
              #print ("msigdb_library:",msigdb_library) 
                  
              # Close the cursor and connection to the database
              cursor.close()  # Close the cursor
              conn.close()  # Close the connection
              
              stop_loop_time = time.time()  # Record the stop time of the loop
              execution_time = stop_loop_time - start_loop_time  # Calculate the execution time
              print(f"Execution time: {execution_time} seconds")  # Print the execution time

            # Filter out non-coding genes if specified
            if filter_non_coding_genes:
                coding_genes_query = "SELECT * FROM codingGenes"  # SQL query to get coding genes
                genedb = json_object['genedb']  # Get the gene database path from the JSON object
                gene_conn = sqlite3.connect(genedb)  # Connect to the gene database
                gene_cursor = gene_conn.cursor()  # Create a cursor object for the gene database
                gene_cursor.execute(coding_genes_query)  # Execute the query to get coding genes
                coding_genes_list = gene_cursor.fetchall()  # Fetch all coding genes
                coding_genes_list = list(map(lambda x: x[0], coding_genes_list))  # Extract the gene symbols
                signature = signature[signature['Genes'].isin(coding_genes_list)]  # Filter the signature to include only coding genes
            
            if 'geneset_name' in json_object:
                # Detail-image path. The server delivers the previously
                # computed gsea result inline as a base64-encoded pickle,
                # so we never touch disk for the data.
                geneset_name = json_object['geneset_name']
                pickle_b64 = json_object['pickle_b64']
                result = pd.read_pickle(io.BytesIO(base64.b64decode(pickle_b64)))
                fig = blitz.plot.running_sum(signature, geneset_name, msigdb_library, result=result.T, compact=True)
                random_num = np.random.rand()  # Generate a random number for unique png filename
                png_filename = f"gsea_plot_{random_num}.png"  # Create a filename for the plot
                fig.savefig(os.path.join(cachedir, png_filename), bbox_inches='tight')  # Save the plot as a PNG file
                print(f'image: {{"image_file": "{png_filename}"}}')
            else:
                # Initial-table path. We always run blitzgsea fresh — Node
                # owns the cache; if we got here the envelope was missing.
                # Pickle the result into a BytesIO and base64-encode it so
                # the server can stash it inside the JSON envelope and feed
                # it back on a later detail-image request.
                start_gsea_time = time.time()
                if __name__ == "__main__":
                    gsea_result = _safe_blitz_gsea(signature, msigdb_library, num_permutations)
                    if gsea_result is None:
                        continue
                    result = _recompute_fdr(gsea_result).T
                    buf = io.BytesIO()
                    result.to_pickle(buf)
                    pickle_b64 = base64.b64encode(buf.getvalue()).decode('ascii')
                    # pickle first, json second: the detail-image path replays the
                    # pickle through blitzgsea and needs the real floats, while only
                    # the json crossing to the client needs the infinities labelled
                    print(f'result: {{"data": {result.map(_finite_or_label).to_json()}, "pickle_b64": "{pickle_b64}"}}')
                stop_gsea_time = time.time()
                gsea_time = stop_gsea_time - start_gsea_time
                print(f"GSEA time: {gsea_time} seconds")
    else:
        pass  # Do nothing if there is no input from stdin
except (EOFError, IOError):
    pass  # Handle EOFError and IOError exceptions gracefully

# Function to extract plot data for GSEA visualization (NOT currently being used, but will be used for generating client side gsea plots)
def extract_plot_data(signature, geneset, library, result, center=True):
     print("signature", signature)
     print("result", result)
     print("geneset", geneset)
     print("library", library)
     signature = signature.copy()  # Create a copy of the signature DataFrame
     signature.columns = ["i", "v"]  # Rename columns to 'i' and 'v'
     signature = signature.sort_values("v", ascending=False).set_index("i")  # Sort by 'v' in descending order and set 'i' as index
     signature = signature[~signature.index.duplicated(keep='first')]  # Remove duplicate indices, keeping the first occurrence
   
     if center:
         signature.loc[:, "v"] -= np.mean(signature.loc[:, "v"])  # Center the signature values by subtracting the mean
   
     signature_map = {h: i for i, h in enumerate(signature.index)}  # Create a mapping of signature indices
   
     gs = set(library[geneset])  # Get the gene set from the library
     hits = [i for i, x in enumerate(signature.index) if x in gs]  # Find the indices of hits in the signature
   
     running_sum, es = blitz.enrichment_score(np.array(np.abs(signature.iloc[:, 0])), signature_map, gs)  # Compute running sum and enrichment score
     running_sum = list(running_sum)  # Convert running sum to a list
     nn = np.where(np.abs(running_sum) == np.max(np.abs(running_sum)))[0][0]  # Find the index of the maximum absolute running sum
   
     running_sum_str = [str(elem) for elem in running_sum]  # Convert running sum elements to strings
     print(f'result: {{"nn": {nn}, "running_sum": "{",".join(running_sum_str)}", "es": {es}}}')  # Print the result in JSON format
