import path from 'path'
import fs from 'fs'
import serverconfig from '#src/serverconfig.js'
import type { MultiomicRankingsRequest, MultiomicRankingsResponse, RouteApi } from '#types'
import { multiomicRankingsPayload } from '#types/checkers'

export const api: RouteApi = {
	endpoint: 'termdb/multiomicRankings',
	methods: {
		get: { ...multiomicRankingsPayload, init },
		post: { ...multiomicRankingsPayload, init }
	}
}

type ParsedFile = { columns: string[]; rows: (string | number | null)[][] }
const fileCache: Map<string, ParsedFile> = new Map()

function stripQuotes(s: string): string {
	if (s.length >= 2 && s[0] === '"' && s[s.length - 1] === '"') return s.slice(1, -1)
	return s
}

function parseTsv(absPath: string): ParsedFile {
	// Naive TSV split — assumes no embedded tabs or newlines within quoted cells.
	// Ranking files are flat tables generated by the panNDA pipeline.
	const text = fs.readFileSync(absPath, 'utf8')
	const lines = text.split(/\r?\n/).filter(l => l.length > 0)
	if (lines.length === 0) return { columns: [], rows: [] }
	const columns = lines[0].split('\t').map(stripQuotes)
	const rows: (string | number | null)[][] = []
	for (let i = 1; i < lines.length; i++) {
		const fields = lines[i].split('\t').map(stripQuotes)
		const row: (string | number | null)[] = fields.map(v => {
			if (v === '' || v === 'NA' || v === 'NaN') return null
			const n = Number(v)
			return Number.isFinite(n) && v.trim() !== '' ? n : v
		})
		rows.push(row)
	}
	return { columns, rows }
}

function init({ genomes }) {
	return async (req, res): Promise<void> => {
		try {
			const q: MultiomicRankingsRequest = (req.method === 'POST' ? req.body : req.query) || {}
			const genome = genomes[q.genome]
			if (!genome) throw 'invalid genome'
			const ds = genome.datasets[q.dslabel]
			if (!ds) throw 'invalid dslabel'
			const cfg = ds.queries?.multiomicRankings as Record<string, string> | undefined
			if (!cfg) throw 'multiomicRankings not configured for this dataset'

			if (!q.key) {
				res.send({ keys: Object.keys(cfg) } satisfies MultiomicRankingsResponse)
				return
			}

			const relPath = cfg[q.key]
			if (!relPath) throw 'invalid key'

			const cacheKey = `${q.genome}|${q.dslabel}|${q.key}`
			let parsed = fileCache.get(cacheKey)
			if (!parsed) {
				const absPath = path.resolve(serverconfig.tpmasterdir, relPath)
				if (!absPath.startsWith(path.resolve(serverconfig.tpmasterdir) + path.sep)) {
					throw 'invalid file path'
				}
				parsed = parseTsv(absPath)
				fileCache.set(cacheKey, parsed)
			}
			res.send({ columns: parsed.columns, rows: parsed.rows } satisfies MultiomicRankingsResponse)
		} catch (e: any) {
			if (e instanceof Error && e.stack) console.log(e)
			res.send({ error: e?.message || String(e) } satisfies MultiomicRankingsResponse)
		}
	}
}
