apiVersion: v1
kind: PersistentVolume
metadata:
  name: proteinpaint-pv
  labels:
    {{- include "proteinpaint.labels" . | nindent 4 }}
spec:
  capacity:
    storage: 1200Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: proteinpaint-pvc
  mountOptions:
    - allow-delete
    - region {{ .Values.storage.region }}
  csi:
    driver: s3.csi.aws.com
    volumeHandle: proteinpaint-pv
    volumeAttributes:
      bucketName: {{ .Values.storage.bucketName | quote }}
      authenticationSource: pod
