apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: proteinpaint-pvc
  labels:
    {{- include "proteinpaint.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1200Gi
  volumeName: proteinpaint-pv
