name: 'Upload rust assets'
description: 'Upload rust assets to latest release'
inputs:
  GITHUB_TOKEN:
    description: 'Github token'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3

    - name: Download Rust Binaries
      uses: actions/download-artifact@v4
      with:
        name: rust-binaries
        path: rust-binaries

    - name: Rename Rust Binaries
      shell: bash
      id: rename_rust_binaries
      run: |
        BRANCH=$(git rev-parse --abbrev-ref HEAD)
        git pull origin $BRANCH 
        PP_TAG="v$(node -p "require('./package.json').version")"
        echo "::set-output name=pp_tag::$PP_TAG"; 
        git fetch --tags --quiet origin $PP_TAG # always use tagged commit for build 
        
        PP_RUST_TAG="$(node -p "require('./rust/package.json').version")";
        RENAMED="rust-binaries-$PP_RUST_TAG-linux-x64.tar.gz"
        tar -czvf "$RENAMED" -C rust-binaries .
        echo "::set-output name=renamed_rust_binaries::$RENAMED";

    - uses: AButler/upload-release-assets@v3.0
      with:
        files: "${{ steps.rename_rust_binaries.outputs.renamed_rust_binaries }}"
        repo-token: ${{ inputs.GITHUB_TOKEN }}
        release-tag: ${{ steps.rename_rust_binaries.outputs.pp_tag }}