#!/bin/bash

rm -rf dist
# Bundle to not worry about `import ... from *.ts` in src files breaking in prod server runtime.
# Note that bundling will lose type information since a d.ts file is not generated by tsc, 
# but full type-checking will still be available in sjpp and proteinpaint monorepo environments
# when --conditions=sjpp/dev is set as part of running dev and test scripts.
esbuild src/index.ts --bundle --platform=neutral --outdir=dist --format=esm --sourcemap
