#!/bin/bash

set -e

echo "type checking ..."
npx tsc

CHECKERSRAW=src/checkers
CHECKERSDIR=dist

echo "creating type checker code at $CHECKERSDIR"
echo "npx typia generate --input $CHECKERSRAW --output $CHECKERSDIR"
npx typia generate --input $CHECKERSRAW --output $CHECKERSDIR
npx prettier src/checkers/* --no-semi --use-tabs --write

DOCSDIR=../../public/docs/server
echo "building documentation at $DOCSDIR ..."
rm -rf $DOCSDIR/*
npx typedoc --json $DOCSDIR/server.json

# assumes `npm run doc` has autogenerated documentation under public/docs/
d3='<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/4.13.0/d3.min.js" integrity="sha512-RJJ1NNC88QhN7dwpCY8rm/6OxI+YdQP48DrLGe/eSAd+n+s1PXwQkkpzzAgoJe4cZFW2GALQoxox61gSY2yQfg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>' # pragma: allowlist secret
nav="<script src='/docs/nav.js'></script>"
subheader="<div class='docs-subheader'><span class='code-snippet'>./docs/build.sh</span> # to regenerate</div>"
# mv $DOCSDIR/index.html-e $DOCSDIR/index.html
find $DOCSDIR \( -type d -name .git -prune \) -o -type f -print0 | xargs -0 sed -i -e "s|<body>|<body>$d3$nav$subheader|g"
rm -rf $DOCSDIR/**/*.*-e
rm -rf $DOCSDIR/*.*-e
rm -rf $DOCSDIR/**/.*-e
rm -rf $DOCSDIR/.*-e

echo "extract types from html in $DOCSDIR"
../../augen/src/extractTypesFromHtml.js $DOCSDIR > $DOCSDIR/extracts.json

echo "bundling type checker code for browser ..."
npx esbuild $CHECKERSDIR/routes.ts --bundle --platform=browser --format=esm --sourcemap > $DOCSDIR/checkers.js
