/* 
	usage: `npx tsx emitCheckers.ts [inputFile]`

	if inputFile is specified, that file will be read and the transformed content will be echoed
	if not, `src/routes` dir will be scanned as input files and the transformed content will be written to 'dist'

  This script is a work-around to not require typia markups in ts src/ files,
  to make it easier for consumer code to import src type definitions without
  having to install typia plugins for a bundler. 

	Instead, this emitter will read the contents of route ts files
	and add the typia checker code that esbuild + plugins could use
	at build time.

	TODO: may deprecate exporting type checkers if these are not used during runtime,
	or may only use for testing and not prod
*/
import fs from 'fs'
import path from 'path'
import { execSync } from 'child_process'

process.removeAllListeners('warning')

const __dirname = import.meta.dirname
const routesDir = './src/routes'
const cwd = path.join(__dirname, routesDir)
const inputFile = process.argv[2]
const files = inputFile ? [inputFile.replace(cwd, '')] : fs.globSync('*.ts', { cwd })
//const uniquesTypeIds = new Set()
const transitiveExports: string[] = []
files.sort()
// const exportCheckers: string[] = []

const autoGeneratedComment = `// this file was auto-generated using 'npm run generate' or 'npm run dev' from the shared/types dir\n`

for (const f of files) {
	//if (f.includes('aiProjectAdmin') && !f.includes('termdb.sampleScatter')) continue
	const outfile = path.join(__dirname, `../../server/checkers/${f}`)
	if (fs.existsSync(outfile)) continue

	const importLines: string[] = [`import type { RoutePayload } from '../src/routes/routeApi.ts'`]
	const exportPayloads: string[] = []
	const exportCheckers: string[] = []
	const _ = await import(`${routesDir}/${f}`)
	for (const [key, val] of Object.entries(_)) {
		const { request, response } = val as any
		const typeIds = [request?.typeId, response?.typeId].filter(t => t != undefined)
		if (!typeIds.length) continue
		importLines.push(`import type { ${typeIds.join(', ')} } from '../src/routes/${f}'`)
		if (key.endsWith('Payload')) {
			exportPayloads.push(`export const ${key}: RoutePayload = {
				request: {typeId: '${(val as any).request.typeId}'},
				response: {typeId: '${(val as any).response.typeId}'}
			}`)
		}
		// for (const typeId of typeIds) {
		// 	if (!typeId || uniquesTypeIds.has(typeId)) continue
		// 	uniquesTypeIds.add(typeId)
		// 	exportCheckers.push(`export const valid${typeId} = createValidate<${typeId}>()`)
		// }
	}

	if (exportPayloads.length || exportCheckers.length) {
		const contents =
			autoGeneratedComment +
			importLines.join('\n') +
			'\n\n' +
			exportPayloads.join('\n') +
			'\n\n' +
			exportCheckers.join('\n') +
			'\n'

		fs.writeFileSync(outfile, contents, { encoding: 'utf8' })
		transitiveExports.push(`export * from './${f}'`)
	}
}

if (transitiveExports.length) {
	const contents = autoGeneratedComment + transitiveExports.join('\n') + '\n'

	const outfile = path.join(__dirname, `./checkers/index.js`)
	fs.writeFileSync(outfile, contents, { encoding: 'utf8' })
}

execSync(`npx prettier ./checkers/*.ts  --no-semi --use-tabs --write`)
