import type { TermTypes } from '#shared/terms.js'
import type { DbRows } from '#types'

export type MsgToUser = {
	type: 'text'
	text: string
}

// *** Scaffold Temp Types *** //
export type SummaryScaffold = {
	plotType: 'summary'
	tw1: string
	tw2?: string
	tw3?: string
	filter?: string
	chartType?: 'violin' | 'boxplot' | 'sampleScatter' | 'barchart' // optional, only for summary plot for now
}
export type DEScaffold = {
	plotType: 'dge'
	filter1: string
	filter2: string
	filter?: string
	method?: 'edgeR' | 'DESeq2' | 'limma' // optional, default to edgeR if not provided
}

export type MatrixScaffold = {
	plotType: 'matrix'
	twLst: string[]
	divideBy?: string
	filter?: string
}

export type GenomeBrowserScaffold = {
	plotType: 'genomeBrowser'
	genomeBrowserPhrase?: string
	genePhrase?: string
	filter?: string
}

export type SurvivalScaffold = {
	plotType: 'survival'
	term?: string
	term2: string
	filter?: string
}

export type HierarchicalScaffold = {
	plotType: 'hiercluster'
	hierarchicalPhrases: string[]
	filter?: string
	filterTvs?: any // tvslst object generated by generateFilterTerm(), ready for UI
}

export type HierarchicalGeneExpressionScaffold = {
	plotType: 'hiercluster'
	hierarchicalPhrase: string
	filter?: string
	filterTvs?: any // tvslst object generated by generateFilterTerm(), ready for UI
}

export type PrebuiltScatterScaffold = {
	plotType: 'prebuiltscatter'
	name: string
	colorBy?: string
	shapeBy?: string
	divideBy?: string
	filter?: string
}

export type Scaffold =
	| SummaryScaffold
	| DEScaffold
	| MatrixScaffold
	| HierarchicalScaffold
	| PrebuiltScatterScaffold
	| GenomeBrowserScaffold
	| SurvivalScaffold

// Helper functions to determine scaffold type
export function isSummaryScaffold(s: Scaffold): s is SummaryScaffold {
	return 'tw1' in s
}

export function isDEScaffold(s: Scaffold): s is DEScaffold {
	return 'filter1' in s && 'filter2' in s
}

export function isMatrixScaffold(s: Scaffold): s is MatrixScaffold {
	return 'twLst' in s
}

export function isHierarchicalScaffold(s: Scaffold): s is HierarchicalScaffold {
	return s.plotType === 'hiercluster'
}

// *** Entity Temp Types *** //
type TermTypes =
	| 'dictionary'
	| typeof TermTypes.GENE_EXPRESSION
	| typeof TermTypes.DNA_METHYLATION
	| typeof TermTypes.GENE_VARIANT
	| typeof TermTypes.PROTEOME_ABUNDANCE
	| typeof TermTypes.SSGSEA

export type Entity = {
	termType: TermTypes
	phrase: string
	logicalOperator?: '&' | '|' // optional, for filters
}

export type SummaryPhrase2EntityResult = {
	tw1: [Entity]
	tw2?: [Entity]
	tw3?: [Entity]
	filter?: Entity[] // These might use logical operators
}

export type DEPhrase2EntityResult = {
	filter1: Entity[] // will actually be nested structure later on
	filter2: Entity[] // will actually be nested structure later on
	filter?: Entity[]
	method?: 'edgeR' | 'DESeq2' | 'limma' // optional, default to edgeR if not provided
}

export type HierPhrase2EntityResult = {
	phrases: Entity[]
	filter?: Entity[]
}

export type SurvivalPhrase2EntityResult = {
	/** When the survival term was named in the prompt and resolved to a single dataset
	 *  term, this is the matched name (string). When the prompt did not name one (or was
	 *  ambiguous), this is the full list of survival terms available in the dataset
	 *  (DbRows[]) so the UI can prompt the user to pick one. */
	term?: string | DbRows[]
	term2: Entity
	filter?: Entity[]
}

export type MatrixPhrase2EntityResult = {
	twLst: Entity[]
	divideBy?: Entity
	filter?: Entity[]
}

export type PrebuiltScatterPhrase2EntityResult = {
	name: string
	colorBy?: Entity | 'null' // null means user explicitly wants to remove coloring
	shapeBy?: Entity | 'null' // null means user explicitly wants to remove shaping
	divideBy?: Entity
	filter?: Entity[]
}

export type Phrase2EntityResult =
	| SummaryPhrase2EntityResult
	| DEPhrase2EntityResult
	| HierPhrase2EntityResult
	| MatrixPhrase2EntityResult
	| PrebuiltScatterPhrase2EntityResult
	| SurvivalPhrase2EntityResult

// JSON schema types for the filter tree returned by evaluateFilterTerm()
export type FilterLeafNode = { leaf: string }
export type FilterOperatorNode = { op: '&' | '|'; left: FilterTreeNode; right: FilterTreeNode }
export type FilterTreeNode = FilterLeafNode | FilterOperatorNode
export type FilterTreeResult = { sexpr: string; tree: FilterTreeNode }

// The JSON schema definition passed to the LLM prompt
export const filterTreeJsonSchema = {
	type: 'object',
	required: ['sexpr', 'tree'],
	properties: {
		sexpr: { type: 'string', description: 'The full S-expression as a string' },
		tree: { $ref: '#/$defs/node' }
	},
	$defs: {
		node: {
			oneOf: [
				{
					type: 'object',
					required: ['op', 'left', 'right'],
					properties: {
						op: { type: 'string', enum: ['&', '|'] },
						left: { $ref: '#/$defs/node' },
						right: { $ref: '#/$defs/node' }
					},
					additionalProperties: false
				},
				{
					type: 'object',
					required: ['leaf'],
					properties: {
						leaf: { type: 'string' }
					},
					additionalProperties: false
				}
			]
		}
	},
	additionalProperties: false
}
