// esbuild is currently not able to use dynamically imported variable file paths),
// cannot use fs.readdirSync() or await import('./routes/${filename}') in app.ts),
// see https://github.com/evanw/esbuild/issues/700
// export const routeFiles = fs.readdirSync(path.join(serverconfig.binpath), '/routes')), {encoding: 'utf8'), recursive: false})

// must add route file paths below so that esbuild knows exactly what to bundle),
// since dynamic import plugin is not yet supported
export const routeFiles = [
	import('./aiProjectAdmin/aiProjectAdmin.ts'),
	import('./aiProjectAdmin/aiProjectSelectedWSImages.ts'),
	import('./aiProjectAdmin/aiProjectTrainModel.ts'),
	import('./chat/route.ts'),
	import('./grin2/route.ts'),
	import('./j2/AbyB.ts'),
	import('./j2/junctions.ts'),
	import('./j2/onesampletk.ts'),
	import('./routes/brainImaging.ts'),
	import('./routes/brainImagingSamples.ts'),
	import('./routes/burden.ts'),
	import('./routes/correlationVolcano.ts'),
	import('./routes/dataset.ts'),
	import('./routes/deleteWSITileSelection.ts'),
	import('./routes/dsdata.ts'),
	import('./routes/dzimages.ts'),
	import('./routes/gdc.maf.ts'),
	import('./routes/gdc.mafBuild.ts'),
	import('./routes/termdb.topMutatedGenes.ts'),
	import('./routes/gene2canonicalisoform.ts'),
	import('./routes/genelookup.ts'),
	import('./routes/genesetEnrichment.ts'),
	import('./routes/genesetOverrepresentation.ts'),
	import('./routes/genomes.ts'),
	import('./routes/healthcheck.ts'),
	import('./routes/hicdata.ts'),
	import('./routes/hicgenome.ts'),
	import('./routes/hicstat.ts'),
	import('./routes/img.ts'),
	import('./routes/isoformlst.ts'),
	import('./routes/ntseq.ts'),
	import('./routes/pdomain.ts'),
	import('./routes/sampledzimages.ts'),
	import('./routes/samplewsimages.ts'),
	import('./routes/saveWSIAnnotation.ts'),
	import('./routes/snp.ts'),
	import('./routes/termdb.DE.ts'),
	import('./routes/termdb.animatedBubbleChart.ts'),
	import('./routes/termdb.brainRegions.ts'),
	import('./routes/termdb.bubbleHeatmap.ts'),
	import('./routes/termdb.dapVolcano.ts'),
	import('./routes/termdb.diffMeth.ts'),
	import('./routes/termdb.violinBox.ts'),
	import('./routes/termdb.categories.ts'),
	import('./routes/termdb.cluster.ts'),
	import('./routes/termdb.cohort.summary.ts'),
	import('./routes/termdb.cohorts.ts'),
	import('./routes/termdb.config.ts'),
	import('./routes/termdb.descrstats.ts'),
	import('./routes/termdb.dmr.ts'),
	import('./routes/termdb.facet.ts'),
	import('./routes/termdb.isoformAvailability.ts'),
	import('./routes/termdb.geneRanking.ts'),
	import('./routes/termdb.numericcategories.ts'),
	import('./routes/termdb.percentile.ts'),
	import('./routes/termdb.proteome.ts'),
	import('./routes/termdb.rootterm.ts'),
	import('./routes/termdb.runChart.ts'),
	import('./routes/termdb.sampleImages.ts'),
	import('./routes/termdb.sampleScatter.ts'),
	import('./routes/termdb.singleSampleMutation.ts'),
	import('./routes/termdb.termchildren.ts'),
	import('./routes/termdb.termsbyids.ts'),
	import('./routes/termdb.topTermsByType.ts'),
	import('./routes/termdb.topVariablyExpressedGenes.ts'),
	import('./routes/tileserver.ts'),
	import('./routes/wsimages.ts'),
	import('./routes/wsisamples.ts'),
	import('./routes/termdb.filterTermValues.ts'),
	import('./routes/termdb.profileFormScores.ts'),
	import('./routes/profile.polar2.ts'),
	import('./routes/profile.barchart2.ts'),
	import('./routes/profile.radar2.ts'),
	import('./routes/profile.radarFacility2.ts'),
	import('../routes/profile.impressionDistribution.ts'),
	import('./singleCell/dataRoute.ts'),
	import('./singleCell/DEgenesRoute.ts'),
	import('./singleCell/plotsRoute.ts'),
	import('./singleCell/samplesRoute.ts')
]
