// esbuild is currently not able to use filter dynamically imported variable file paths,
// cannot use fs.readdirSync() or await import('../routes/${filename}') in app.ts, see https://github.com/evanw/esbuild/issues/700
// export const routeFiles = fs.readdirSync(path.join(serverconfig.binpath, '/routes'), {encoding: 'utf8', recursive: false})

// must add route file paths below so that esbuild knows exactly what to bundle,
// since dynamic import plugin is not yet supported
export const routeFiles = [
	'../routes/brainImaging.ts',
	'../routes/brainImagingSamples.ts',
	'../routes/burden.ts',
	'../routes/correlationVolcano.ts',
	'../routes/dataset.ts',
	'../routes/dsdata.ts',
	'../routes/dzimages.ts',
	'../routes/gdc.maf.ts',
	'../routes/gdc.mafBuild.ts',
	'../routes/gdc.topMutatedGenes.ts',
	'../routes/gene2canonicalisoform.ts',
	'../routes/genelookup.ts',
	'../routes/genesetEnrichment.ts',
	'../routes/genesetOverrepresentation.ts',
	'../routes/genomes.ts',
	'../routes/healthcheck.ts',
	'../routes/hicdata.ts',
	'../routes/hicgenome.ts',
	'../routes/hicstat.ts',
	'../routes/isoformlst.ts',
	'../routes/ntseq.ts',
	'../routes/pdomain.ts',
	'../routes/sampledzimages.ts',
	'../routes/samplewsimages.ts',
	'../routes/snp.ts',
	'../routes/termdb.DE.ts',
	'../routes/termdb.boxplot.ts',
	'../routes/termdb.categories.ts',
	'../routes/termdb.cluster.ts',
	'../routes/termdb.cohort.summary.ts',
	'../routes/termdb.cohorts.ts',
	'../routes/termdb.config.ts',
	'../routes/termdb.descrstats.ts',
	'../routes/termdb.numericcategories.ts',
	'../routes/termdb.percentile.ts',
	'../routes/termdb.rootterm.ts',
	'../routes/termdb.sampleImages.ts',
	'../routes/termdb.singleSampleMutation.ts',
	'../routes/termdb.singlecellDEgenes.ts',
	'../routes/termdb.singlecellData.ts',
	'../routes/termdb.singlecellSamples.ts',
	'../routes/termdb.termchildren.ts',
	'../routes/termdb.termsbyids.ts',
	'../routes/termdb.topTermsByType.ts',
	'../routes/termdb.topVariablyExpressedGenes.ts',
	'../routes/termdb.violin.ts',
	'../routes/tileserver.ts',
	'../routes/wsimages.ts'
]
