import type { Div, Elem, SvgG, SvgSvg, SvgText } from '../../types/d3'
import type { PlotConfig } from '#mass/types/mass'
import type { TableCell, TableColumn, Menu } from '#dom'
import type { DataEntry, DEImage, TermWrapper } from '#types'
import type { ValidatedVolcanoSettings } from './settings/Settings'

/** Attributes are added in the view model
 * to the response data for rendering. */
export type DataPointEntry = DataEntry & {
	/** color indicating significance */
	color: string
	/** If true, the fill opacity increases to show the highlight color */
	highlighted: boolean
	/** x coordinate */
	x: number
	/** y coordinate */
	y: number
	/** radius */
	radius: number
	/** Indicate if the point is significant */
	significant: boolean
}

type DEVolcanoPlotConfig = PlotConfig & {
	/** Array of confounders. Default is [] */
	confounderTws: TermWrapper[]
	/** Data points highlighted in the volcano plot. Default is []*/
	highlightedData: string[]
	samplelst: {
		groups: {
			name: string
			samplelst: string[]
		}[]
	}
	/** Custom group term */
	tw: TermWrapper
	termType: 'geneExpression'
}

type SCCTPlotConfig = PlotConfig & {
	sample: string
	columnName: string
	categoryName: string
	termType: 'singleCellCellType'
}

/** Final config created in getPlotConfig() */
export type VolcanoPlotConfig = DEVolcanoPlotConfig | SCCTPlotConfig

/** Data needed to render the scales, plot, etc.
 * Generated by the view model  */
export type VolcanoPlotDimensions = {
	logFoldChangeLine: { x: number; y1: number; y2: number }
	plot: { width: number; height: number; x: number; y: number }
	top: { x: number; y: number }
	svg: { width: number; height: number }
	xAxisLabel: { x: number; y: number }
	xScale: { x: number; y: number; scale: any }
	yAxisLabel: { x: number; y: number; text: string }
	yScale: { x: number; y: number; scale: any }
}

export type VolcanoOpts = {
	holder: Elem
	controls: Elem
	termType: string
	diffAnalysisInteractions?: any
	confounderTws?: TermWrapper[]
	highlightedData?: string[]
	samplelst: {
		groups: {
			name: string
			samplelst: string[]
		}[]
	}
	overrides?: ValidatedVolcanoSettings
	parentId?: string
}

/** Main dom elements created on init() */
export type VolcanoDom = {
	holder: Elem
	/** Either the elem passed from parent component or created
	 * div from the holder. */
	controls: Elem
	/** Div set aside for showing user error messages */
	error: Elem
	/** Loading message */
	wait: Elem
	/** Tooltip for data points */
	tip: Menu
	/** Menu for action buttons above the volcano plot */
	actionsTip: Menu
}

/** this.volcanoDom in view */
export type VolcanoPlotDom = {
	/** Holder for action buttons above the images and plot */
	actions: Div
	/** Holder for data points, p value line, and fold change line */
	plot: SvgG
	pValueTable: Div
	/** Holder for plot, axis labels, and title */
	svg: SvgSvg
	/** Term info */
	top: SvgG
	/** X axis */
	xAxis: SvgG
	/** X axis label */
	xAxisLabel: SvgText
	/** Y axis */
	yAxis: SvgG
	/** Y axis label */
	yAxisLabel: SvgText
}

export type VolcanoPValueTableData = {
	columns: TableColumn[]
	rows: TableCell[][]
	height: number
}

type TermInfoEntry = {
	/** Not in use */
	// color: string;
	/** Formated label to show */
	label: string
	/** x coord */
	x: number
	/** Not in use */
	// rectX: number
}

/** Formatted data from the view model */
export type VolcanoViewData = {
	images: DEImage[]
	termInfo: { y: number; first: TermInfoEntry; second: TermInfoEntry } | undefined
	plotDim: VolcanoPlotDimensions
	pointData: DataPointEntry[]
	pValueTableData: VolcanoPValueTableData
	statsData: { label: string; value: number }[]
	/** special logic per termtype for userActions */
	userActions: {
		noShow: Set<string>
	}
}
