### Get examples for gdc 
# genes
GET https://api.gdc.cancer.gov/genes/ENSG00000084073
Content-Type: application/json

###
# ssms
GET https://api.gdc.cancer.gov/ssms/
Content-Type: application/json
filters: {"op":"=","content":{"field":"consequence.transcript.transcript_id","value":["ENST00000407796"]}}

###
## files
# vcf
GET https://api.gdc.cancer.gov/files/
Content-Type: application/json
filters: {"op":"and","content":[{"op":"in","content":{"field":"cases.submitter_id","value":["TCGA-CK-4948","TCGA-D1-A17N","TCGA-4V-A9QX","TCGA-4V-A9QM"]}},{"op":"=","content":{"field":"files.data_type","value":"Gene Expression Quantification"}}]}

###
# bam
GET https://api.gdc.cancer.gov/files/d853e541-f16a-4345-9f00-88e03c2dc0bc
Content-Type: application/json

###
## annotations
# entity_id
GET https://api.gdc.cancer.gov/annotations/
    ?filters={"op":"in","content":{"field":"entity_id","value":["e0d36cc0-652c-4224-bb10-09d15c7bd8f1","25ebc29a-7598-4ae4-ba7f-618d448882cc","fe660d7c-2746-4b50-ab93-b2ed99960553"]}}
Content-Type: application/json

###

# annotation_id
GET https://api.gdc.cancer.gov/annotations/
    ?filters={"op":"=","content":{"field":"annotation_id","value":"5ddadefe-8b57-5ce2-b8b2-918d63d99a59"}}
Content-Type: application/json

###
## cases
GET https://api.gdc.cancer.gov/cases/70fc011c-0f22-4026-9d72-87351126203a
Content-Type: application/json

###
## cases
#file
GET https://api.gdc.cancer.gov/cases/
?filters={"op":"in","content":{"field":"files.file_id","value":"df80679e-c4d3-487b-934c-fcc782e5d46e"}}
Content-Type: application/json

###
POST https://api.gdc.cancer.gov/v0/graphql
Content-Type: application/json
Authorization: Bearer xxx
X-REQUEST-TYPE: GraphQL

query gdc_bam_file($filters: FiltersArgument, $first: Int){
  repository{
    files{
  		aggregations{
        cases__samples__sample_type{
          buckets{
            key
            doc_count
          }
        }
      }
      hits(filters: $filters, first:$first){
        total
        edges{
          node{
            id
            experimental_strategy
            file_size
            associated_entities{
              hits{
                edges{
                  node{
                    entity_submitter_id
                    entity_type
                    case_id
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

{
  "first":10,
  "filters":{"op":"in","content":{"field":"file_id","value":"df80679e-c4d3-487b-934c-fcc782e5d46e"}}
}



### gdc bam slice query
## bam file uuid
GET https://api.gdc.cancer.gov/files/
# ?filters={"op":"in","content":{"field":"file_id","value":"df80679e-c4d3-487b-934c-fcc782e5d46e"}}
?filters={"op":"and","content":[{"op":"in","content":{"field":"file_id","value":"df80679e-c4d3-487b-934c-fcc782e5d46e"}}]}
&fields=file_size,experimental_strategy,associated_entities.entity_submitter_id,associated_entities.entity_type,associated_entities.case_id,id,cases.samples.sample_type

###
## files from case_id
GET https://api.gdc.cancer.gov/files/
?filters={"op":"and","content":[{"op":"=","content":{"field":"cases.case_id","value":"02e6f999-24f2-4ad2-9b92-df3ee2b082e5"}},{"op":"=","content":{"field":"data_category","value":"Sequencing Reads"}}]}
&fields=file_size,experimental_strategy,associated_entities.entity_submitter_id,associated_entities.entity_type,associated_entities.case_id,id,cases.samples.sample_type

###
## files from case_id
GET https://api.gdc.cancer.gov/files/
?filters={"op":"and","content":[{"op":"in","content":{"field":"cases.submitter_id","value":"TCGA-D8-A1JC"}},{"op":"=","content":{"field":"data_category","value":"Sequencing Reads"}}]}
&fields=file_size,experimental_strategy,associated_entities.entity_submitter_id,associated_entities.entity_type,associated_entities.case_id,id,cases.samples.sample_type

###