name: Publish Docker Image

on:
  workflow_dispatch:
    inputs:
      build_secret:
        type: string
        description: Build secret

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Check secret
        run: |
          if [ "${{ github.event.inputs.build_secret }}" != "${{ secrets.BUILD_SECRET }}" ]; then
            echo "Wrong build secret."
            exit 1
          fi

      - name: Check user permission
        run: echo "Publish Docker Image"
