name: Publish Docker Image

on:
  workflow_dispatch:
    inputs:
      build_secret:
        type: string
        description: Build secret

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Check secret
        run: |
          if [ "${{ github.event.inputs.build_secret }}" != "${{ secrets.BUILD_SECRET }}" ]; then
            echo "Wrong build secret."
            exit 1
          fi

      - name: Check user permission
        id: check
        uses: scherermichael-oss/action-has-permission@master
        with:
          required-permission: write
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        run: |
          echo $CR_PAT | docker login ghcr.io -u stjude --password-stdin
        env:
          CR_PAT: ${{ secrets.PAT }}

      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: '16'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@stjude'
      - run: |
          npm ci
          cd container
          ./build.sh -m "ghcr.io/stjude/"
          TAG="$(node -p "require('./package.json').version")"
          docker push ghcr.io/stjude/ppserver:$TAG
          docker push ghcr.io/stjude/ppfull:$TAG
          docker push ghcr.io/stjude/ppserver:latest
          docker push ghcr.io/stjude/ppfull:latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}