name: Publish Blat Server Image

on:
  workflow_dispatch:
    inputs:
      build_secret:
        type: string
        description: Build secret

  push:
    branches:
      - add-blat-server-image

jobs:
  check-user-permissions:
    runs-on: ubuntu-22.04
    steps:
      - name: Check user permission
        uses: stjude/proteinpaint/.github/actions/check-user-permissions@master
        with:
          BUILD_SECRET: ${{ secrets.BUILD_SECRET }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_BUILD_SECRET: ${{ github.event.inputs.build_secret }}

  build:
    needs: check-user-permissions
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Login to Github
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ inputs.GITHUB_ACTOR }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          cd container/blat
          sh build.sh
          
          docker push ghcr.io/stjude/blat:latest
