name: "Release Packages, Optional Image"

on:
  push:
    branches:
      - release-chain
      - fake-release
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '.**ignore'
      - 'docs/**'
      # TODO: what if package.dependencies, files were updated?
      # this is meant to avoid triggering the on.push event for the version bump
      - '**package*.json'

  workflow_dispatch:
    inputs:
      build_secret:
        type: string
        description: Build secret

jobs:
  unit_test:
    uses: ./.github/workflows/CI-unit.yml
    secrets: inherit # pragma: allowlist secret

  integration_test:
    uses: ./.github/workflows/CI-integration.yml
    secrets: inherit # pragma: allowlist secret

  publish_packages:
    needs: [unit_test, integration_test]
    uses: ./.github/workflows/CD-publish-packages.yml
    secrets: inherit # pragma: allowlist secret

  publish_app_image:
      if: ${{ github.ref_name }} == 'publish-app-image'
      needs: [ publish_packages ]
      uses: ./.github/workflows/CD-publish-app-image.yml
      secrets: inherit # pragma: allowlist secret