name: Run Tests and Check Coverage

on:
  push:
    branches:
      - master
      - fake-master
      - testCI
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

jobs:
  test:
    if: (github.event_name == 'workflow_call') || (github.event_name == 'push' && github.event.head_commit.author.email != 'PPTeam@STJUDE.ORG') || (github.event_name == 'pull_request')
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v3
      with:
          fetch-depth: 10

    - uses: actions/setup-node@v3
      with:
          cache: 'npm'
          node-version: '20'

    - run: npm ci
      env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Run Tests with Coverage
      run: npm run test:coverage

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage/
